### ISSUE TITLE
Form field as array

### ISSUE THREAD

**Issue by vsamal** [skydiver/october-plugin-forms#106]
Hi,

thanks for great plugin!

I'm using some form fields as array for dynamic input:

name="product[' . $id . ']" value=...

This fields in email are correct and in JSON data in the table as well.

In Magic Forms view on backend if you want to see detail od record the plugin show this error on attached image.

![snimek obrazovky 2018-04-25 v 12 17 36](https://user-images.githubusercontent.com/23217692/39239953-b45353f4-4882-11e8-8718-1cbbea1d9f29.png)

Please, it is possible fix it for use arrays in the detail of form?

thank you

Vaclav

**Comment by skydiver** [comment]
Hello @vsamal 

Can you post your form so i can test?

Thanks.-

**Comment by vsamal** [comment]
Hello @skydiver 

my code is posted:

`<form data-request="genericForm::onFormSubmit">
    
        <input name="_token" type="hidden" value="Aa4AOo6BTaqpVvSw6wHHn8csfyGYpDO1fqydXQC6">
    
        <div id="genericForm_forms_flash"></div>    
             
        <input type="hidden" name="price" class="form-control" value="60.00">
        <input type="hidden" name="orderno" class="form-control" value="180426002">
        
        <input type="hidden" name="instock[24]" value="Stamp red">
        <input type="hidden" name="instock[26]" value="tamp blue">
        <input type="hidden" name="instock[28]" value="tamp green">

        <input type="text" name="name" value="">
        <input type="email" name="email" value="">
        
        <input class="form-control btn btn-primary" name="action" type="submit" value="BUY">
                
</form>`

thanks

V.

**Comment by skydiver** [comment]
Hello @vsamal 
I've fixed the bug, here is how your data will look:

![image](https://user-images.githubusercontent.com/578784/39392085-7ad7cfba-4a85-11e8-9876-783fc0ee7db9.png)

**Comment by zlobec** [comment]
This doesn't work:
```
<input type="hidden" name="product[1][quantity]" value="2">
<input type="hidden" name="product[1][price]" value="3.50">
<input type="hidden" name="product[1][total]" value="7.00">
```
Or it's just me?
Regard,
Darjan

**Comment by skydiver** [comment]
Hello @zlobec 

You're right, i never tested with more than 1 level.

Now appears to be finally fixed. Will be released in the next version.

![image](https://user-images.githubusercontent.com/578784/41074321-f2e8fd72-69dd-11e8-8817-d96c2f8289f9.png)

**Comment by zlobec** [comment]
@skydiver Thanks. The fix does parse data in the backend nicely, but there is an error sending notifications:

ErrorException: nl2br() expects parameter 1 to be string, array given in /vendor/twig/twig/lib/Twig/Environment.php(378) : eval()'d code:65

Probably an array is sent to the mail class?
Regard,
Darjan

**Comment by zlobec** [comment]
Never mind. I was still using an old mail template which did not iterate through arrays correctly.

Thanks again for the update!
Regard,
Darjan
