### ISSUE TITLE
Skip DB issue

### ISSUE THREAD

**Issue by leonaze** [skydiver/october-plugin-forms#108]
Hi,
On a new project when I use Skip DB to true I have this error:
"Type error: Argument 2 passed to Martin\Forms\Classes\BackendHelpers::replaceToken() must be of the type string, null given, called in /flex/storage/***/***/test/plugins/martin/forms/classes/SendMail.php on line 39" on line 76 of /flex/storage/***/***/test/plugins/martin/forms/classes/BackendHelpers.php
And I don't know why !

**Comment by skydiver** [comment]
Thanks @leonaze 

This will be fixed on v1.4.9

**Comment by leonaze** [comment]
Thanks @skydiver

**Comment by zlobec** [comment]
@skydiver is there any info when the 1.4.9. version will be available? GDPR is here and I need to disable database storage of data on the server. Thanks for the info.

**Comment by skydiver** [comment]
Sorry for the late @zlobec 

Was on the beta channel.

It's already pushed to stable channel.

These version has a lot of changes, so if you find errors or strange behaviors, please report!

**Comment by zlobec** [comment]
Thanks for the push.
