### ISSUE TITLE
File not uploading in Magic Forms

### ISSUE THREAD

**Issue by sabir1210** [skydiver/october-plugin-forms#109]
Hlw, I'm using Magic Form to post forms.
Drag & drop is not working...! I used generic form file didn't uploaded ....!
I used Upload ajax forms file wasn't uploaded...!!!
Why is this aLL???

**Comment by skydiver** [comment]
Hello @sabir1210 

There is a few discussion about the upload component, this is the more recent: https://github.com/skydiver/october-plugin-forms/issues/114
