### ISSUE TITLE
Add user as an email recipient 

### ISSUE THREAD

**Issue by wertykid** [skydiver/october-plugin-forms#110]
Hello,
I have a form on my website whereby the customer would sign up for an event via a form. When the customer submits his details together with his email, I would like the customer to receive an email based on the options that he has entered on the form. How can I do so?

**Comment by skydiver** [comment]
Hello @wertykid 

You need to edit `martin.forms::mail.autoresponse` template.

On the body of the message, you can access any field of your form with this syntax:

`{{ data.yourfield }}`

Ex:
`{{ data.name }}`
`{{ data.email }}`


![image](https://user-images.githubusercontent.com/578784/41147430-c91519f4-6adc-11e8-94dc-985e70fe3a57.png)
