### ISSUE TITLE
I get an error when trying to submit my data using ajax 

### ISSUE THREAD

**Issue by Antar74** [skydiver/october-plugin-forms#111]
Hello, thankyou for your plugin. It seems to be useful but so far I'm having trouble doing so. I get the following message when trying to submit 

"Class 'DOMDocument' not found" on line 465 of /var/www/html/octobercms/install-master/vendor/erusev/parsedown-extra/ParsedownExtra.php

**Comment by skydiver** [comment]
Hello @Antar74 

This is not a October or plugin error.

A Google search reveals you have a missing php extension: https://stackoverflow.com/questions/14395239/class-domdocument-not-found
