### ISSUE TITLE
Form renders success flash but email is never sent

### ISSUE THREAD

**Issue by sergiocastrovale** [skydiver/october-plugin-forms#115]
Hi guys, I'm having an urgent issue - wasn't expecting it and my deadline is today :(

Whenever I send an email using this plugin, I get no errors whatsoever but emails are never sent. To be sure, I switched my credentials and am using gmail's - but the problem is the same. 

*Form*

```
<form data-request="{{ __SELF__ }}::onFormSubmit" data-request-validate>
    {{ form_token() }}

    <div class="row">
        <div id="{{ __SELF__ }}_forms_flash" class="col-md-12"></div>
    </div>

    <div class="row">
        <div class="col-md-6">
            <div class="form-group">
                <input type="text" id="name" name="name" class="form-control" placeholder="Nome">
                <div data-validate-for="name" class="has-error"></div>
            </div>
        </div>

        <div class="col-md-6">
            <div class="form-group">
                <input type="text" id="email" name="email" class="form-control" placeholder="E-mail">
                <div data-validate-for="email" class="has-error"></div>
            </div>
        </div>
    </div>

    <div class="row">
        <div class="col-md-12">
            <div class="form-group">
                <textarea id="message" name="message" class="form-control" cols="30" rows="7" placeholder="Mensagem"></textarea>
                <div data-validate-for="message" class="has-error"></div>
            </div>

        </div>
    </div>

    <div class="send">
        <input id="submit" type="submit" value="Enviar" class="btn btn-primary">
    </div>
</form>
````

*.env file*

```
MAIL_DRIVER=smtp (tried with sendmail too)
MAIL_HOST=smtp.gmail.com
MAIL_PORT=587
MAIL_USERNAME=myemail@gmail.com
MAIL_PASSWORD=mypassword
MAIL_ENCRYPTION=tls
```

*OctoberCMS mail configuration*

![screenshot_1](https://user-images.githubusercontent.com/8822036/40501034-9ba7ffae-5f7e-11e8-9137-31bb1778c5c2.jpg)

Whenever I send an email, the only thing I see in the XHR responses is this, which is weird - shouldn the POST response contain HTML?

![screenshot_2](https://user-images.githubusercontent.com/8822036/40501111-cffe01a4-5f7e-11e8-9d42-520f4183183b.jpg)

Hope anyone can help me out. Thanks!

**Comment by skydiver** [comment]
Sorry @sergiocastrovale but never used gmail smtp server...
Probably you need to use smtp as email method, but don't know the gmail config 😞
