### ISSUE TITLE
Backend Stop working after upgrade 1.4.9

### ISSUE THREAD

**Issue by willouch** [skydiver/october-plugin-forms#116]
Backend Stop working after upgrade..

Parse error: syntax error, unexpected '?', expecting variable (T_VARIABLE)
/home/trux.fr/public_html/plugins/martin/forms/classes/BackendHelpers.php line 80

Thks

**Comment by skydiver** [comment]
Hey @willouch, which version of php are you using?

**Comment by matteotrubini** [comment]
Nullable types (`?string`) feature is introduced in PHP 7.1 while October require PHP 7.0
Maybe it can be replaced by `string $replacement = null` at least until main requirements shifts up?

**Comment by skydiver** [comment]
> Nullable types (?string) feature is introduced in PHP 7.1 

Yeah, i was afraid of that ...

Fixed using @matteotrubini suggestion, the quick fix was already pushed to stable channel.
