### ISSUE TITLE
ReplyTo field

### ISSUE THREAD

**Issue by gregoryloichot** [skydiver/october-plugin-forms#117]
How can I add the address the user fill in to the "replyTo" field?

**Comment by skydiver** [comment]
First you need the name of the email field of the form.
Then add that name to the *ReplyTo Email Field*, under *Notifications Settings* on component settings.

**Comment by CptMeatball** [comment]
Why not include this in the documentation?

**Comment by skydiver** [comment]
@CptMeatball i'm writing new documentation and this will be included
