### ISSUE TITLE
autoresponse not working

### ISSUE THREAD

**Issue by vosco88** [skydiver/october-plugin-forms#118]
Hi, 

I am using your plugin and want to enable autoresponse in generic ajax form.
One issue is when I do not specify subject it gives this error:
`Undefined index: mail_resp_subject" on line 91 of C:\laragon\www\tmavaochutnavka\plugins\martin\forms\classes\SendMail.php`

Then when I fill it the subject, form is submitted but the autoresponse email is not send. The notification email is working as expected.

Could you help me to find the issue?

**Comment by skydiver** [comment]
Hello @vosco88 
Can you paste your form html and component config so i can help?

Thanks.-

**Comment by vosco88** [comment]
Sure,
sorry for the formatting it somehow did not work as a whole.
here is the component
`[genericForm companiesContactForm] 
group = "contactUs"
messages_success = "Your form was successfully submitted"
messages_errors = "There were errors with your submission"
mail_enabled = 1
mail_recipients[] = "tibor@tmavadegustacia.sk"
mail_resp_enabled = 1
mail_resp_field = "jvoscek@gmail.com"
mail_resp_from = "tibor@tmavadegustacia.sk"
mail_resp_subject = "Subject"
inline_errors = "disabled"
sanitize_data = "disabled"
anonymize_ip = "disabled"
recaptcha_theme = "light"
recaptcha_type = "image"
recaptcha_size = "normal"
==`

and the form
`<form class="shadow-lg p-8 " data-request="{{ companiesContactForm }}::onFormSubmit">`
`{{ form_token() }}`
    `<div id="{{ companiesContactForm }}_forms_flash"></div>`
`    <div class="flex flex-wrap -mx-3 mb-6">`
    `<div class="w-1/2 md:w-1/2 px-3 mb-6">`
        `<label class="block uppercase tracking-wide text-grey-darker text-xs font-bold mb-2" for="name">Meno a priezvisko</label>`
        `<input type="text" id="name" name="name" class="form-control appearance-none block w-full bg-grey-lighter text-grey-darker border border-grey-lighter py-3 px-4">`
        `</div>`
    `<div class="w-1/2 md:w-1/2 px-3 mb-6">`
        `<label class="block uppercase tracking-wide text-grey-darker text-xs font-bold mb-2" for="email">Email</label>`
        `<input type="text" id="email" name="email" class="form-control appearance-none block w-full bg-grey-lighter text-grey-darker border border-grey-lighter py-3 px-4">`
    `</div>`
    `<div class="w-full px-3">`
   ` <label class="block uppercase tracking-wide text-grey-darker text-xs font-bold mb-2" for="email">Sprava</label>`
        `<textarea id="message" name="message" class="form-control appearance-none block w-full bg-grey-lighter text-grey-darker border border-grey-lighter py-3 px-4" rows="8" cols="80"></textarea>`
    `</div>`
    `</div>`
    `<button id="simpleContactSubmitButton" type="submit" class="bg-green hover:bg-green-dark w-full text-white font-bold py-4">Odoslat</button>`

`</form>`

**Comment by laurentcava** [comment]
Hi, 
I have the same problem, but no error is firing.

I never receive auto response email but i receive notification email.
I force mail_resp_field to my email before to try with email from form but that doesn't not work to.

Anyone have an idea ?

thanks

**Comment by skydiver** [comment]
Hello @vosco88

In your case, you are using an email address on the setting `Email Field`.

Here, you need to insert the name of your form input holding the visitor email.

In your case, your input name is `email`, just use this value as your setting.

**Comment by skydiver** [comment]
@laurentcava i think you have the same problem
