### ISSUE TITLE
Auto-reponse subject from template

### ISSUE THREAD

**Issue by zlobec** [skydiver/october-plugin-forms#119]
Hi,

I see that the default subject set in the template is not processed when sending an auto-response email. 

I would like to personalize the auto-response subject with form data. How to do that with "mail_resp_subject" property?

Regard,
Darjan

**Comment by skydiver** [comment]
Hi @zlobec and @fredec 

There is a new PR https://github.com/skydiver/october-plugin-forms/pull/135 who adds this feature.

Now you can do: 
![image](https://user-images.githubusercontent.com/578784/51447864-de66df00-1d00-11e9-9538-f75c29b3715e.png)

Hope this helps

**Comment by zlobec** [comment]
Exquisite!
