### ISSUE TITLE
{{__SELF__}} is empty

### ISSUE THREAD

**Issue by Zmove** [skydiver/october-plugin-forms#12]
Hello,

First excellent plugin for october. Flexible and simple to use, congratulation !

However, I encountered a small issue. I followed the instruction you give when you embed the emptyForm component and my form correctly submit the informations.

But the value of {{ __SELF__ }} is empty, so the flash message id is : "_forms_flash" instead of "emptyForm_forms_flash"

If I remove the variable and manually enter the ID it works, but I wonder why that variable is not available.

Alex

**Comment by skydiver** [comment]
Can you tell me the steps to reproduce the error?

**Comment by Zmove** [comment]
Step to reproduce :

To reproduce the error, you just have to create a form without overriding the default partial template. By putting the form code directly in your page, or by embedding a partial, but without override the default template.

The form will work, but the value of {{__SELF__}} will be empty.

I also noticed (when the {{__SELF__}} value works (so when you properly override the default form template by using partial located in /partials/emptyForm/default.htm) that you could change that line :
