### ISSUE TITLE
Recipient selector

### ISSUE THREAD

**Issue by jleinbaugh** [skydiver/october-plugin-forms#121]
Is it possible to create a recipient selector using magic form?  ie, if I have three divisions (sales, parts, service) the user could select from a dropdown menu and the email would be sent to the appropriate email address (choose sales, email sent to sales@company.com)?  Sorry, I'm new to OctoberCMS

**Comment by skydiver** [comment]
Hello @jleinbaugh 

I like the idea, i will see if can be part of the next release (no estimated date yet).

**Comment by skydiver** [comment]
Hello @jleinbaugh 

After spend some time i found this features requires some refactor so i found a quicker approach.

Using the extend feature of the plugin ([more info here](https://skydiver.github.io/october-plugin-forms/docs/advanced/events)) you can easily override the recipients email address.

You need to create a new plugin and work on the boot method of Plugin.php

Here is an example:

```
public function boot() {
    \Event::listen('martin.forms.beforeSaveRecord', function (&$formdata, $component) {

        // Get department input value
        $department = $formdata['department'];

        // Get department email address
        switch ($department) {
            case 'marketing':
                $email = 'marketing@company.com';
                break;
            case 'sales':
                $email = 'sales@company.com';
                break;
            case 'support':
                $email = 'support@company.com';
                break;
            default:
                $email = 'hello@company.com';
                break;
        }

        // Override component mail recipients
        $component->setProperty('mail_recipients', [$email]);

    });
}
```

Of course your form will need a new department input:

```
<select id="department" name="department" class="form-control">
    <option value="marketing">Marketing</option>
    <option value="sales">Sales</option>
    <option value="support">Support</option>
</select>
```

Also, i made an empty plugin to be used for this pourpouse: https://github.com/skydiver/october-plugin-formsextender

Simply replace the boot method with previous code.
