### ISSUE TITLE
No Secret Provided

### ISSUE THREAD

**Issue by jovvybersamin** [skydiver/october-plugin-forms#124]
Hi,

I already added the Site Key and Secret Key in the Magic Forms > ReCaptcha settings, however, when I tried to submit the form I always get an alert with a message of "No Secret Provided".

How can I fix this?

Thanks

**Comment by skydiver** [comment]
Hello @jovvybersamin 

Can you paste your form code and component configuration?

Thanks.-

**Comment by jovvybersamin** [comment]
Hi @skydiver,

I already fixed the issue, I have installed another captcha plugin conflicting to the captcha plugin that already included in the magic form.

Thanks
