### ISSUE TITLE
After submitting it does not show in records

### ISSUE THREAD

**Issue by iBrady** [skydiver/october-plugin-forms#125]
Hi there.

I have installed Magic Forms and I've read the documentation and I am using the example markup.

For some reason, after submitting the form, it will not show any data on the records page. 
It just says "There are no records in this view.".

Could you please help me out?

Thanks in advance.

Edit: Clean installation on localhost also failed to make this work. (Latest version)

**Comment by skydiver** [comment]
Hello @iBrady 

Sadly i cannot help too much with the provided info.

Can you paste your form code?

Are you using the component on a page or a partial?

Thanks.-

**Comment by iBrady** [comment]
Hey!

Thanks for you response.

I am not able to access my computer right now.

However I can tell you what I did:

I installed OctoberCMS, installed Magic Forms. Then I went making a page named “Test”. I simply dragged the Generic AJAX form into the page and saved it.

Then I went to the test page filled in everything and sent it. Then yet the record page was showing no data, also with the recaptcha keys set.

Sorry if it’s a bit messy, sending this from my phone.

Thanks

**Comment by iBrady** [comment]
Hi,

I uninstalled the plugin and reinstalled it within the terminal. 
`php artisan plugin:install Martin.Forms`

It is still not working properly. I can fill in the form on the /test page but it still does not show any results on the records page.

Anything you need to know? I am using the following as partial:

`<form data-request="{{ __SELF__ }}::onFormSubmit">

    {{ form_token() }}

    <div id="{{ __SELF__ }}_forms_flash"></div>

    <div class="form-group">
        <label for="name">Name:</label>
        <input type="text" id="name" name="name" class="form-control">
    </div>

    <div class="form-group">
        <label for="email">Email:</label>
        <input type="text" id="email" name="email" class="form-control">
    </div>

    <div class="form-group">
        <label for="subject">Subject:</label>
        <input type="text" id="subject" name="subject" class="form-control">
    </div>

    <div class="form-group">
        <textarea id="comments" name="comments" rows="8" cols="80"></textarea>
    </div>

    <button id="simpleContactSubmitButton" type="submit" class="btn btn-default">Submit</button>

</form>`

Thanks!
