### ISSUE TITLE
AJAX handler 'genericForm::onFormSubmit' was not found.

### ISSUE THREAD

**Issue by simon511000** [skydiver/october-plugin-forms#126]
Hey, I have a problem with your plugin, every time I test my form, I have the error `AJAX handler 'genericForm::onFormSubmit' was not found.` that appears. If you want, I can email you the login and password of the backend.
https://youtu.be/k2F1GQvG_y0

**Comment by mebdev** [comment]
Is the form in a partial? If so, I was having the same issue. My solution was to keep the actual form in the partial but do the component config on the layout or page.

**Comment by simon511000** [comment]
[my page and my form are in different partials](https://youtu.be/k2F1GQvG_y0), I did not understand what I had to do to fix the problem.

Thank you very much for your help :D

**Comment by spacebeers** [comment]
Sticking this here on the off chance but I was dynamically setting the name of a form to render in the partial. When I move the logic outside the component into the default layout I can't access the page anymore. Any advice is welcome.
