### ISSUE TITLE
Send to different email depending on a choice in the form

### ISSUE THREAD

**Issue by PubliAlex** [skydiver/october-plugin-forms#129]
Hello,

I wonder what is the best way to send email to different addresses depending on a choice made in the form.

Basically, I have "Category" dropdown in my form : 

You want to contact : 
- General
- Technical support
- Commercial support
- etc....

If Technical support is selected, the email needs to be sent to tech@mydomain.com
If Commercial support is selected, the email needs to be send to sales@mydomain.com
etc....

Thank you

**Comment by skydiver** [comment]
Hello @PubliAlex 

Have you seen this example?

https://skydiver.github.io/october-plugin-forms/docs/advanced/events_recipient_selector

**Comment by PubliAlex** [comment]
Hello,

I didn't see this example in the doc, this is exactly what I need. Thank you !
