### ISSUE TITLE
Put the component in partial

### ISSUE THREAD

**Issue by Zmove** [skydiver/october-plugin-forms#13]
Hello,

I'm doing some tests with the plugin, and it seems that you cannot put a form in a partial.

What I mean is that insteaf of calling the component in your page, and override the default template using a partial, I would like to put the component directly in the partial and call it by using 

`{% partial 'myform' %}`

Like that, the form could be configured in the partial directly (validation, messages etc...) and you just embed it when you want.

It works with all plugin I could test (blog etc...) but with this one, when I submit the form I get an error.

> Ajax handler 'emptyForm::onFormSubmit was not found'

Would it be possible to fix it ?

Thanks

Alex

**Comment by skydiver** [comment]
Hey @Zmove, it's this issue related with #12 right?

I will take a look at the problem.

The scenario is to put the component inside a partial and call this partial from a page, right?

**Comment by skydiver** [comment]
Partials can't run ajax handlers defined on the component
* [docs here](http://octobercms.com/docs/cms/partials#dynamic-partials)
* [read here](https://octobercms.com/plugin/support/laminsanneh-flexicontact/ajax-handler-contactformonmailsent-was-not-found)
* [read here](https://octobercms.com/plugin/support/renatio-formbuilder/ajax-handler-renderformonsubmit-was-not-found)

So, here are a few alternatives:

---

**Method 1:**

1 .Insert the component **emptyForm** on the page
2. Configure component parameters
3. Insert `{% component 'emptyForm' %}` on the partial (just the code, don't drag the component)

---

**Method 2:**

If you need to put the same partial/form on differente pages, you can do the same but at layout level

1 .Insert the component **emptyForm** on your layout
2. Configure component parameters
3. Insert `{% component 'emptyForm' %}` on the partial (just the code, don't drag the component)

**Comment by Zmove** [comment]
Hello,

Thank you for this complete answer. I don't know october well yet and I didn't know you cant run ajax handler in partials.

I finally used your method 1. I create my partial with all fields I need and instead of putting the component in my partial, I put it in my page. It's not a big drawback.

Alex
