### ISSUE TITLE
Plugin not working at all

### ISSUE THREAD

**Issue by alanrysis** [skydiver/october-plugin-forms#132]
Hi.

I recently add this plugin to my project in October CMS and nothing seems to work when I click submit button. I follow documentation, step by step but when I render the form and click in the submit button, nothing happens, the page refreshes, even if I configure a success redirect page, some data is added to the URL and just stays there. No Records in the data base.

Maybe I'm missing something. Any guesses of what it is causing this?

Regards.

**Comment by alanrysis** [comment]
Thanks Martin!
Second bullet tip just do the trick 👍 

Regards

**Comment by MiguelDebruyne** [comment]
I had the same problem/solution , searched about an hour for this... Should be in the docs
