### ISSUE TITLE
JavaScript does not execute if Inline errors is set to "display errors"

### ISSUE THREAD

**Issue by multiwebinc** [skydiver/october-plugin-forms#133]
JavaScript only seems to execute if `Inline errors` is set to `JS variable`. if I set it to `display errors`, it doesn't get executed.

**Comment by multiwebinc** [comment]
The `JS on Success` and `JS on Error` scripts are not being executed. Is this as designed? If so, why?

**Comment by skydiver** [comment]
this was fixed
