### ISSUE TITLE
Pass an array of errors to JavaScript

### ISSUE THREAD

**Issue by multiwebinc** [skydiver/october-plugin-forms#134]
It would be great if in the JavaScript you were given an array of error messages so that you could process them:

Here's an example of how it could be done:

**MagicForm.php:**

    public function onFormSubmit() {
        // ... //
        if ($validator->fails()) {
            // ... //
            if ($this->property('inline_errors') == 'display') {
                throw new ValidationException($validator);
            } else {
                throw new AjaxException($this->_exceptionResponse($validator, [
                    'status'  => 'error',
                    'type'    => 'danger',
                    'title'   => $message,
                    'list'    => $validator->messages()->all(),
                    'errors'    => json_encode($validator->messages()->messages()),
                    'jscript' => $this->property('js_on_error'),
                ]));
            }

        }
    }

**flash.htm**

    <script>
        {% if errors %}
            var errors = JSON.parse('{{ errors|raw }}');
        {% endif %}
        {{ jscript|raw }}
    </script>

Then in the `jscript` you have access to the `errors` variable with the keys and respective error messages.

If you're interested I'll submit a PR.

**Comment by skydiver** [comment]
PR merged, thanks @multiwebinc
