### ISSUE TITLE
Email Template Field Issue

### ISSUE THREAD

**Issue by mattpollard0** [skydiver/october-plugin-forms#139]
On the site I'm using, a form submission gets emailed and shows the field entries in a table using the default mail template, however the labels are displayed exactly as they are in the field ID, with underscores in.

Is there any way I can give each field a different ID that gets shown as the field label instead?

![email example](https://user-images.githubusercontent.com/26490859/51616070-3bd97680-1f21-11e9-99c9-db76e7117e50.PNG)

**Comment by skydiver** [comment]
Hello @mattpollard0 

Currently is not possible from the plugin.

You can manually edit email template by going to: Settings > Mail templates > martin.forms::mail.notification and replace line 6.

Using [twig replace](https://twig.symfony.com/doc/2.x/filters/replace.html) function you can change labels underscores to spaces.

Hope it helps.

**Comment by amdad** [comment]
@skydiver Why not incorporate new tag like 
<input name="my_name_zyz" data-label="My name XYZ"> 
So labels in mail will be taken from label tag if label tag exist. What do you think? It can be called `data-label` or `data-maillabel` etc. or maybe even just `label`.
