### ISSUE TITLE
Issue in Mail Auto Respond

### ISSUE THREAD

**Issue by subha-praves** [skydiver/october-plugin-forms#140]
Send Auto Response is not fully featured as like Send Notification. 

One issue I have noticed is there is exception if we don't set mail subject in component, because it hasn't checked for empty , for example $subject  = $properties['mail_resp_subject'];. Therefore if we keep this property empty in component we get exception.

Other one is feature request. As setting tokens is allowed for Send Notification, setting tokens can also be allowed for Auto Response in subject.

One more request is , tokens can be allowed for data fields to be used in subject also.

**Comment by skydiver** [comment]
Hello @subha-praves, thanks for your input.

1. auto-response empty subject will be fixed in next version (1.4.14)
2. auto-response tokens are enabled since latest version (1.4.13)
