### ISSUE TITLE
Custom messages not working

### ISSUE THREAD

**Issue by MiguelDebruyne** [skydiver/october-plugin-forms#141]
I get these standard error messages instead of my custom ones

>The comments field is required.
> The name field is required.
> The email must be a valid email address.

Even though in the component I have these settings

```
[genericForm contactForm]
group = "Contact"
rules[comments] = "required"
rules[name] = "required"
rules[email] = "required|email"
rules[phone] = "numeric"
rules_messages[name.required] = "Gelieve uw naam in te vullen"
rules_messages[comments.required] = "U bent uw vraag vergeten te stellen"
rules_messages[email.required] = "Gelieve uw email toe te voegen"
rules_messages[email.email] = "Uw e-mail adres klopt niet"
rules_messages[phone.numeric] = "Uw telefoonnummer klopt niet"
messages_success = "Uw formulier was succesvol verzonden. We nemen zo spoedig mogelijk contact met u op!"
messages_errors = "Er zijn problemen met het versturen van het formulier"
reset_form = 1
inline_errors = "display"
sanitize_data = "disabled"
anonymize_ip = "disabled"
recaptcha_theme = "light"
recaptcha_type = "image"
recaptcha_size = "normal"
```

Both the flash messages are displayed correcly though, it's just the custom messages.
It's pretty clear in the docs on how you should it, so what am I missing here?

Edit: I've been able to make it work with 'inline errors: display errors. (Maybe it would be a good idea for your docs to link to the October docs because I, making my first site, wasn't aware that I had to search there for answers. https://octobercms.com/docs/ajax/extras#error-messages). But I haven't found how I can get that flash error message to appear on top on invalid submit while having chosen inline errors.

Edit: 
Added component code
I asked this question on Stackoverflow: https://stackoverflow.com/questions/54923299/magic-forms-custom-messages-not-working

**Comment by skydiver** [comment]
Hello @MiguelDebruyne, sorry for the late reply.

I don't fully understand the problem you are getting.

You don't see your custom error messages?

Thanks.-

**Comment by MiguelDebruyne** [comment]
I updated my question with the component code

So, when the form is submitted correctly the correct messages displays: 
`messages_success : "Uw formulier was succesvol verzonden. We nemen zo spoedig mogelijk contact met u op!"`

But the separate error message rules likes `rules_messages[name.required]` are not correct, I get the default message in English. Not the one I said it should show according to

`rules[name] = "required"` and `rules_messages[name.required] = "Gelieve uw naam in te vullen"`
