### ISSUE TITLE
Magic Forms with validator.js bootstrap 3

### ISSUE THREAD

**Issue by SegaWeb** [skydiver/october-plugin-forms#143]
Good day!
I would like to use this plugin (http://1000hz.github.io/bootstrap-validator/) to validate the form. How to connect it correctly? 
Make it so that it automatically connects when loading magic forms controller.

**Comment by skydiver** [comment]
Hello @SegaWeb 

Never used that plugin so i can't help.

Let's see if anyone else can help.

**Comment by SegaWeb** [comment]
Advise, please, how to expand the magic form controller. Use, for example, my js script with your plugin. How to do it right? Only small example )
