### ISSUE TITLE
how to call init() 'trait ReCaptcha'

### ISSUE THREAD

**Issue by two4zero** [skydiver/october-plugin-forms#144]
error : classes/ReCaptcha.php : 37 line

> Call to a member function getLocale() on null
> .../plugins/martin/forms/classes/ReCaptcha.php line 37

```
private function getReCaptchaLang($lang='') {
    if(BackendHelpers::isTranslatePlugin()) { $lang = '&hl=' . $this->activeLocale = $this->translator->getLocale(); }
    return $lang;
}
```

-----------------------------------------------------------

how to call init() in 'trait ReCaptcha'
classes/ReCaptcha.php

```
public function init() {
    if(BackendHelpers::isTranslatePlugin()) {
        $this->translator = Translator::instance();
    }
}
```

**Comment by skydiver** [comment]
Merged, thanks.-
