### ISSUE TITLE
May be an detailed example or tutorial?

### ISSUE THREAD

**Issue by informas** [skydiver/october-plugin-forms#146]
I am trying to test this plugin (an old version 1.4.6.1) by following the instructions in the "QuickStart" section, just as I have interpreted them and I can not get the emails sent.

The steps I have followed are the following:

1) I created a blank page (/test-form)
2) I added the "Generic Ajax Form" component as "GenericForm1", I setup it and save it.
Appears in markup
{% component 'genericForm1'%}

3) I invoke MYDOMAIN.COM/test-form
fill in the data and press the submit button.

4) The answer is that a new page is invoked:
  MYDOMAIN.COM/test-form?_token=ui0a...j0i4eEqouAmauZBV&name=Some+name&email=address%40of.email.com&subject=My+subject&comments=The+comments

The email is not sent.

There are nothing registered in the table.

No error message appears.

Am I missing something to add?

What I can be doing wrong?

Thanks in advance.

**Comment by skydiver** [comment]
You need to add:

```
{% framework %}
{% framework extras %}
```

More info here: https://octobercms.com/docs/ajax/introduction

Docs will be updated shortly
