### ISSUE TITLE
Add support rainlab.translate

### ISSUE THREAD

**Issue by ribsousa** [skydiver/october-plugin-forms#15]
Great work!

You plan to add suport to translations!

thanks!

**Comment by skydiver** [comment]
Sure, will be a nice feature, but never used rainlab.translate on my own plugins.

Can you tell me what will be translated? Backend, frontend?

Any examples?


Thanks.-

**Comment by ribsousa** [comment]
Models attributes and message

See docs [plugin](http://octobercms.com/plugin/rainlab-translate)

**Comment by skydiver** [comment]
This was added on #19 and #23 

(Thanks to @mariavilaro for the help)
