### ISSUE TITLE
Add flash & recaptcha partial to each component folders

### ISSUE THREAD

**Issue by ghost** [skydiver/october-plugin-forms#151]
Hello,

I have a small feature request about the recaptcha and flash partials. Actually, they are in a '/partials' folder because they are shared between all components. Sounds logical.

However, the fact to not be present in the component folder prevent to call them using this syntax in your theme.

`{% partial '@recaptcha.htm' %}`

When called from the theme, it seems that the @syntax only look in the used component folder, so, by doing that, it throw an error saying the recaptcha partial cannot be found.

I don't have solution to that, I don't think we can browse between component folders using the @syntax.

The solution I suggest is to **create a recaptcha.htm and flash.htm in each component folders**, that directly reference the partials that are in /partial folder (to continue to share code).

What do you think about it ? I think it could be really useful because we rarely need to customize the recaptcha partial.

**Comment by PubliAlex** [comment]
@skydiver any update about this suggestion ?

**Comment by skydiver** [comment]
Hello @PubliAlex 

Do you wanna submit a pull request for this?

**Comment by PubliAlex** [comment]
No problem, if the idea is validated, I can work for a PR.
