### ISSUE TITLE
Identification of the subpage with the form

### ISSUE THREAD

**Issue by pierzo** [skydiver/october-plugin-forms#152]
Hi, I have a portfolio plugin made with page builder. Then I put the generic form component in the layout. And now on any project site I have contact form. Is it possible for the form to save the link to the database from which it was sent?
I need something like this to work:
```
<div class="form-group">
        <input type="hidden"  name="name" value="{{ url_current() }}" class="form-control">
    </div>
```

**Comment by skydiver** [comment]
Hey @pierzo 

Looks good to me, probably i will use a better name for the hidden name, like:

`<input type="hidden" name="page" value="{{ url_current() }}" class="form-control">`

**Comment by pierzo** [comment]
But this method does not work, it does not save in DB page's url

**Comment by pierzo** [comment]
I solve the problem, I need to delete a space after url_current()}}
