### ISSUE TITLE
$record model attached to martin.forms.afterSaveRecord

### ISSUE THREAD

**Issue by boxxroom** [skydiver/october-plugin-forms#153]
Firstly i'd like to commend you for a great plugin, this plugin has saved huge amounts of time in form additions.

Secondly, I'd like to access the `Martin\Forms\Models\Record` model using the event provided from the `Martin\Forms\Classes\MagicForm` class to manipulate the data / file further.

```php
// FIRE AFTER SAVE EVENT
Event::fire('martin.forms.afterSaveRecord', [&$post, $this]);
```

Is it possible to retrieve the `Martin\Forms\Classes\MagicForm` with bound `System\Models\File` model from the `$this` object or would it require an extra argument which would supply the `Martin\Forms\Classes\MagicForm` model.

i.e
```php
// FIRE AFTER SAVE EVENT
Event::fire('martin.forms.afterSaveRecord', [&$post, $this, $record]);
```
Thanks in advance

**Comment by skydiver** [comment]
Hello @boxxroom 

Have you seen this article? https://skydiver.github.io/october-plugin-forms/docs/advanced/events/

Look `Magic Form Extender` section.

**Comment by boxxroom** [comment]
Hi @skydiver 

No, I hadn't seen this thank you.

I have created a plugin which in theory does exactly the same as https://skydiver.github.io/october-plugin-forms/docs/advanced/events/ and extends the `martin.forms.afterSaveRecord` event within the `boot` method with a few additions for communicating with the api.

That said, the `Magic Form Extender` still only provides two arguments `$formdata, $component` but not the model `Martin\Forms\Classes\MagicForm` of the newly saved record - unless I am missing something.

My PR adds the `Martin\Forms\Classes\MagicForm` as the third argument so on event extension you also have the newly created `Martin\Forms\Classes\MagicForm` object data at hand.

My use case is with using the `UploadForm` class and needing the saved files. What I believe is that files are uploaded before the form submission, on form submission (`onFormSubmit`) the file data isn't available in the `$_POST` data by the time it reaches the `martin.forms.afterSaveRecord` event, by passing the `Martin\Forms\Classes\MagicForm` saved record as the third argument to the `martin.forms.afterSaveRecord` event it gives access to the `files` relation.

Hope this all makes sense.

Again, thanks in advance.

**Comment by zakir1929** [comment]
Yes record model must be passed on Events so it can be used further. Right now I need saved record id in event aftersave method but it was not passed into that. I would plugin author to please add that feature. 

Thanks
