### ISSUE TITLE
Using submitted values in mail template

### ISSUE THREAD

**Issue by hill79** [skydiver/october-plugin-forms#155]
I've created a custom form which works fine with the system email template, all values are sent through as expected.  I want to create my own template, but when I try to reference the input value using (eg) {{ first_name }} in the template, there's just a blank space when the email arrives.  Am I missing something?

**Comment by PubliAlex** [comment]
Hmm, I believe submitted datas are embed in an object like {{ data }} or {{ record }}

Try using {{ data.first_name }} or {{ record.fist_name }} and see if it works

**Comment by damsfx** [comment]
**[Using Form Variables](https://skydiver.github.io/october-plugin-forms/docs/notifications/variables/)**

````
{{ record.id }}      # the record id stored on the database
{{ record.ip }}      # the ip address of the sender
{{ record.date }}    # date when form was submitted

{{ form.xxx }}       # where "xxx" is the name of an existing form field
{{ form.full_name }} # the value of the field with attribute name="full_name"
````

**Comment by nolyboms** [comment]
Hello @hill79, did you manage to output the values in the autoresponse mail?

Tried
``
{{ form_data_arr.XXX }}
{{ form_data.XXX }}
``
..but didn't work. -_-
