### ISSUE TITLE
Send new record to admin email?

### ISSUE THREAD

**Issue by Antar74** [skydiver/october-plugin-forms#158]
Hello

I'm really new to October CMS plugins, and need to ustomize your Magic Forms plugin. I have it working perfectly... I just need to send every new record in the data base to an admin email. There is no option to do that from the plugin settings. How can I achieve this? Should I modify the partial?

thanx!

**Comment by damsfx** [comment]
>  I just need to send every new record in the data base to an admin email.

What type of recording?  
The ones from MagicForm or all the models?

In the first case, just use the notification capabilities of the component : 

- Send Notifications : checked
- Mail Template : code of the one you just have freshly create to suit your needs.
