### ISSUE TITLE
Dynamic properties

### ISSUE THREAD

**Issue by quimalguero** [skydiver/october-plugin-forms#159]
Hi @skydiver ,

I need to assign the email recipients and others fields dynamically. I try using the code below, and if i look the component values are ok, but don't work:

```
function onEnd()
{
  $this->page->components['leadform']->setProperty('mail_subject','Formulari de pre-reserva' . $this->record_detail->title);
  $this->page->components['leadform']->setProperty('mail_recipients',[$this->record_detail->email_reserva, $this->record_detail->email_reserva2]);

}

**Comment by kombimedia** [comment]
Hi @quimalguero ,

Did you manage to get this working? I've tried with onRun and onRender but still can't get it working.

Cheers

**Comment by quimalguero** [comment]
Hi @kombimedia,

I tried on every cyclelife handler but don't work.

**Comment by kombimedia** [comment]
Thanks for coming back to me @quimalguero. Surly there is a way for this to work..

@skydiver , Are you able to give some insight into how we can dynamically update component properties? Would really appreciate your help.

Cheers,

**Comment by skydiver** [comment]
Guys, have you look at this example?
https://skydiver.github.io/october-plugin-forms/docs/advanced/events_recipient_selector/

**Comment by kombimedia** [comment]
@skydiver , Thanks for coming back to us.

I have created a plugin to extend Magic Forms via the event listener. In my form I have a hidden field that holds the form recipient's email address. This field is populated from the database, depending on the "business listing" that is selected.

When I try to retrieve the hidden field value in my plugin via the `$formdata` variable i get this error.

Error message:

```
"Undefined index: recipient" on line 22 of /home/vagrant/development/nationalpark/plugins/responsive/form/Plugin.php"
```

Any ideas? Maybe I'm missing something simple?

My form field:

```
<div class="form-group">
  <label for="recipient">Recipient:</label>
  <input type="hidden" id="recipient" name="recipient" class="form-control" value="{{ record.email }}">
</div>
```

My plugin.php:

```
<?php namespace Responsive\Form;

use App;
use System\Classes\PluginBase;

class Plugin extends PluginBase
{
    public function pluginDetails() {
        return [
            'name'        => 'Form',
            'description' => 'Extend Magic Forms plugin.',
            'author'      => 'Responsive',
            'icon'        => 'icon-puzzle-piece',
            'homepage'    => ''
        ];
    }
    public function boot() {
      \Event::listen('martin.forms.beforeSaveRecord', function (&$formdata, $component) {

          // Get recipient input value
          $email = $formdata['recipient'];

          // Override component mail recipients
          $component->setProperty('mail_recipients', [$email]);

      });
    }
}
```
Thank you or your help.

**Comment by kombimedia** [comment]
@skydiver  - Hey, any ideas on the reason for my error when trying to retrieve form data via the `$formdata` variable - as above?

Cheers,
