### ISSUE TITLE
Search field on the records page.

### ISSUE THREAD

**Issue by 75gas** [skydiver/october-plugin-forms#160]
Hi! 
When I use the search field: 

> "SQLSTATE[HY000]: General error: 1 near "group": syntax error (SQL: select count(*) as aggregate from "martin_forms_records" where (((lower(martin_forms_records.id) LIKE %j%) or (lower(martin_forms_records.group) LIKE %j%) or (lower(martin_forms_records.ip) LIKE %j%) or (lower(martin_forms_records.form_data) LIKE %j%))) and "martin_forms_records"."deleted_at" is null)" on line 664 of /vendor/laravel/framework/src/Illuminate/Database/Connection.php

Could you please help me out?

Thanks in advance.

**Comment by PubliAlex** [comment]
Can confirm the error

**Comment by damsfx** [comment]
October v 458  
MagicForm v 1.4.16  

Didn't get any errors !
