### ISSUE TITLE
{{ form.xxx }} give me an error when send confirmation

### ISSUE THREAD

**Issue by faselunare** [skydiver/october-plugin-forms#165]
Hi, it seems that I can't send a confirmation email to the sender...

in the Recipent field i add: {{ form.email }} once addedd i see this on the component [{{ form.email }}]

when i try to send a form, i get this error
```
Address in mailbox given [{{ form.email }}] does not comply with RFC 2822, 3.6.2." on line 355 of /home/web/public_html/website/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Mime/Headers/MailboxHeader.php
```

Thanks

**Comment by skydiver** [comment]
Hello @faselunare 

Can you post your form?

Thanks (and sorry for the delay)

**Comment by faselunare** [comment]
Hi i'm not able now, website refer to an event (and the event is ended)
