### ISSUE TITLE
add email notification to Queues

### ISSUE THREAD

**Issue by dobeweb** [skydiver/october-plugin-forms#166]
when submit a form with email notification, it takes a long time to send the email. 
is there any way add email notification to a queue job?

**Comment by skydiver** [comment]
Hello @dobeweb 

You can use events: https://skydiver.github.io/october-plugin-forms/docs/advanced/events/

You can disable sending emails and with https://github.com/skydiver/october-plugin-formsextender add your own queue for mail sending.
