### ISSUE TITLE
File input / mail attachment support

### ISSUE THREAD

**Issue by Zmove** [skydiver/october-plugin-forms#17]
Hello,

It seems that the file input form type isn't supported. It would be a great addition to let users attach a file to the form managed with magic form.

Regards,

Alex

**Comment by skydiver** [comment]
AJAX files upload it's "too complicated" (you can read more [here](https://github.com/octobercms/october/issues/2428#issuecomment-257048976).

I think the best solution will be creating a new component who refresh the page (or redirect) to upload files.

Definitely it's something i want to see on the plugin, but, honestly don't know when.

**Comment by Zmove** [comment]
Thanks for the answer, do you think it can help ?

(Frontend File Uploader plugin) [https://octobercms.com/plugin/netsti-uploader]

**Comment by skydiver** [comment]
These options where added on v1.3.0

Still in beta, if you want to use right now, enable "Bleeding edge updates" option on **config/cms.php**
