### ISSUE TITLE
$.ajax is not a function

### ISSUE THREAD

**Issue by mrhaha80** [skydiver/october-plugin-forms#170]
Dear Experts,

Anyone can help me at http://ringolow.interzol.com/contact-us ?
When click submit, an error below occurred, i have not idea what is going wrong. 

2390611b6dced525f552ea34446a0d70-1573285328:371 Uncaught TypeError: $.ajax is not a function

the 1st line of code below is the error occurred

      `  return $.ajax(requestOptions)
            .fail(function(jqXHR, textStatus, errorThrown) {
                if (!isRedirect) {
                    $el.trigger('ajaxFail', [context, textStatus, jqXHR])
                }
                if (loading) loading.hide()
            })`

Thanks

**Comment by skydiver** [comment]
Did you include October AJAX framework?

Take a look here:
https://skydiver.github.io/october-plugin-forms/docs/quickstart/
https://octobercms.com/docs/ajax/introduction#framework-script

**Comment by mrhaha80** [comment]
Hi Skydiver,

Yes. it is there
![Capture](https://user-images.githubusercontent.com/23629310/68537658-d61c8500-03a2-11ea-8949-d7fbe9f1de6a.PNG)


Thanks
Anthony
