### ISSUE TITLE
Component into partials 

### ISSUE THREAD

**Issue by bomja** [skydiver/october-plugin-forms#171]
Hello,
thank you for a great plugin!
Working well if component selected into the page but, when I use component("Generic AJAX Form") into the partials: notification emails, reset form, validation, auto reply - not working, but new record is appeared into the records.

Possible to fix it?

Regards

**Comment by skydiver** [comment]
Hello @bomja 

You need to use the component on a page or layout, take a look here: https://github.com/skydiver/october-plugin-forms/issues/57#issuecomment-300921334
