### ISSUE TITLE
Auto-response functionality

### ISSUE THREAD

**Issue by rangrage** [skydiver/october-plugin-forms#18]
Thank you for the auto-response functionality, it is working very well, however I would like to kindly request passing the form field values to the auto-response as well. 

I would like to send a copy of the form data in the auto-response message, I've tried using the template that you have set in the notification but it does not capture the data. 

Thank you for your kind assistance.

**Comment by skydiver** [comment]
The data should be already there.

Just put the name of your field (on the template) like:

```
{{ name }}
{{ email }}
{{ message }}
```

**Comment by rangrage** [comment]
Perfect! Thanks you :)
