### ISSUE TITLE
translate plugin

### ISSUE THREAD

**Issue by SpurnyMarek** [skydiver/october-plugin-forms#181]
Is it possible to use the translate plugin to translate flash messages or rules messages? thanks
![MagicForm](https://user-images.githubusercontent.com/43445347/72189675-c4387c00-33fd-11ea-82d4-f8a946f414ec.PNG)

**Comment by mjauvin** [comment]
@SpurnyMarek Yes, just use Rainlab.Translate Message Translation page

**Comment by mjauvin** [comment]
The success and error messages in the Form Widget will show up when you scan for messages, just add the translations you want in Message Translation page

**Comment by SpurnyMarek** [comment]
thanks for advice, it works well

**Comment by hkan** [comment]
@mjauvin is it possible to make custom attributes translatable too? I am using them but they don't show up on translations page.
