### ISSUE TITLE
Autoresponse messages not being sent

### ISSUE THREAD

**Issue by rangrage** [skydiver/october-plugin-forms#182]
I have an issue with the autoreponse messages not being sent. 

I am using SSL mail config, and I am receiving the notification messages but not the autoresponse messages. The data is also captured in the database successfully. 

Can you please let me know what the problem could be, and how to fix this? 

Many thanks
Reez

**Comment by skydiver** [comment]
Hey @rangrage 

Sounds like a problem with the mail server.

If i had to imagine something, i will say the server finds suspicious the sender or recipient address, like and address sending to himself.
