### ISSUE TITLE
Allow twig filters in subject

### ISSUE THREAD

**Issue by PubliAlex** [skydiver/october-plugin-forms#183]
Hello,

Would it be possible to allow twig filters in mail subject.

An example of use case ? Actually, when you do `{{ record.date }}`, the date in sent in english format : Y/m/d

For french people like me, the date needs to be in the following format : d/m/Y

Allowing twig filters would resolve this problem (and probably more) as I could do `{{ record.date|date('d/m/Y') }}`

Best regards,

Alex

**Comment by mjauvin** [comment]
Side note: Y/m/d is the INTERNATIONAL format... m/d/Y is the english one.

**Comment by PubliAlex** [comment]
Good catch ! ;)

**Comment by skydiver** [comment]
Hey @PubliAlex 

I've spent some time looking at this and loading twig on the backend doesn't look easy.

I hate to add settings for specific issues like this, but i can't think in a better alternative.

![CleanShot 2020-02-29 at 17 37 01](https://user-images.githubusercontent.com/578784/75614690-223e3180-5b1a-11ea-8db5-41a32103a555.png)

**Comment by PubliAlex** [comment]
Sorry for the late reply, just got a child.. 👶, your solution seems to be perfect.

**Comment by skydiver** [comment]
congratulations @PubliAlex!

this feature was added on v1.4.20
