### ISSUE TITLE
Error when sending form; Handler AJAX 'genericForm::onFormSubmit' is not found.

### ISSUE THREAD

**Issue by GORobert** [skydiver/october-plugin-forms#186]
Hey,
i'm trying to get this plugin running. It works on page, but when i create partial with genericForm component and load in staticPage i get this error. Does this plugin not work with partials?
Is there a workaround?

**Comment by GORobert** [comment]
Ok i noticed that i can add partial to the layout, and then it works. But many pages use my layout, and i would like to use my partial with genericForm component only for certain static pages. Is there a way to do so? Or to pass component to layout somehow from partial, so layouts sees that component and can handle it's ajax method?

**Comment by FlusherDock1** [comment]
Just add [genericForm] code in your staticPages layout, and put markup of your form with `genericForm::onFormSubmit` in partial so you can add it as snippet to the page.
