### ISSUE TITLE
Stored Records / Records Viewer / not visible at backend

### ISSUE THREAD

**Issue by wi-wi** [skydiver/october-plugin-forms#187]
Hi,

I can acces the magicforms plugin in at the backend (located under CMS), yet it does not show an entry as: Stored Records / Records Viewer

as on:
https://skydiver.github.io/october-plugin-forms/docs/backend/records/

**Comment by pierzo** [comment]
Hi, same for me! After submit I see no error and database (sqlite) i empty. MF ver. 1.4.19 OCMS ver. 464. Earlier everything working fine.
