### ISSUE TITLE
From Name property

### ISSUE THREAD

**Issue by GORobert** [skydiver/october-plugin-forms#188]
When sending email you should be able to set From Name to custom text instead email - that looks more professional for clients.
`$message->from($address, $name = null);`
Would be great if From name could be customized in the component in addition to From email ( ['mail_resp_from'] )
Or would be also great to add Event before sending email to be able to hook to Mail:sendTo function to extend that manually.
Thanks

**Comment by skydiver** [comment]
Hello @GORobert 

You can customize this name from October email settings:

![image](https://user-images.githubusercontent.com/578784/80781882-6b2a5a80-8b4a-11ea-9bf9-7095a9756dbe.png)

I'm missing something?

**Comment by dijodill** [comment]
> Hello @GORobert
> 
> You can customize this name from October email settings:
> 
> ![image](https://user-images.githubusercontent.com/578784/80781882-6b2a5a80-8b4a-11ea-9bf9-7095a9756dbe.png)
> 
> I'm missing something?

Hi,

Magic Forms is really a great plugin.

But as @GORobert mentioned Magic Form is not fetching the sender name from october mail configuration setting and sending mail without the sender name.

It will be great if you can provide any solution for that.

Thanks in advance

**Comment by skydiver** [comment]
For the record: this setting will be added on Magic Forms v2
