### ISSUE TITLE
Form validation depends on third-party api request

### ISSUE THREAD

**Issue by kskonovalov** [skydiver/october-plugin-forms#189]
Hello!

**What i'm trying to do:**
I have a form, which is added to page as snippet.
After submitting the result i need to create an account with **third-party api** (using curl).
Now i use [events](https://skydiver.github.io/october-plugin-forms/docs/advanced/events/) to submit a request to api (_martin.forms.afterSaveRecord_), and it works.

**The problem is:**
Sometimes there could be an error (for example, user already exists on that **third-party service**), and i don't know **how to return this error back to frontend & user**, so he'll change the form fields.

I read the [Validation](https://skydiver.github.io/october-plugin-forms/docs/validation/validation/) part, but didn't understand where and how can i apply it to my form

**Comment by skydiver** [comment]
Hello @kskonovalov 

You can throw an `AjaxException`

Something like:

```
\Event::listen('martin.forms.beforeSaveRecord', function (&$formdata, $component) {
    throw new \AjaxException([
        '#genericForm_forms_flash' => 'My error message'
    ]);
});
```

Docs will be updated with a better example

**Comment by kskonovalov** [comment]
Hi, @skydiver! Thank you very much!

**Comment by skydiver** [comment]
Hey @kskonovalov 

Docs where updated: https://skydiver.github.io/october-plugin-forms/docs/events/custom_validation/

Will be great some feedback.

**Comment by kskonovalov** [comment]
Hi, @skydiver !
It's much more clear now, thank you!
Few things to improve:
You missed ',' in
`['remoteError' => 'something failed]`
And i think it's better to figure out how to transfer error message to html partial, like:
`<strong>{{ remoteError }}</strong>`
instead of hardcoded text error

**Comment by kskonovalov** [comment]
Also i found i can just do it (with ajax form) as:
In plugin extender 'martin.forms.beforeSaveRecord':
`throw new ValidationException(['Error' => $errorMessage]);`
and in form partial:
`<div class="alert alert-danger" data-validate-error></div>`

and it works

**Comment by skydiver** [comment]
Doc where updated.

Thanks @kskonovalov for the help

**Comment by kskonovalov** [comment]
@skydiver please add link to https://skydiver.github.io/october-plugin-forms/docs/events/custom_validation/ in documentation navigation in sidebar
