### ISSUE TITLE
Using Form Variables

### ISSUE THREAD

**Issue by hackolein** [skydiver/october-plugin-forms#190]
Hey,

in the  doc reads `{{ form.xxx }}` but for me it doesn't work. Is that a doc mistake? For me works `{{ data.xxx }} `

**Comment by skydiver** [comment]
Hey @hackolein 

In email subject you can use form and record.

I see there is no mention to use variables on the email templates.

I will update the docs mentioning you can use variables on both places.

Thanks for flagging this.

**Comment by skydiver** [comment]
Docs where updated: https://skydiver.github.io/october-plugin-forms/docs/notifications/variables/

Thanks @hackolein
