### ISSUE TITLE
Duplicate entries 

### ISSUE THREAD

**Issue by rangrage** [skydiver/october-plugin-forms#193]
Hi Martin, 

I've noticed that some form submissions are being duplicated in the backend, when I check the timestamps the created_at time is identical and the record can be duplicated 2 or 3 times. 

This only happens occasionally though. Have you encountered this before, and what could be the cause? 

Thanks
Reez

**Comment by skydiver** [comment]
Hey @rangrage 

I will start by disabling the submit button after form submit to be sure.

**Comment by rangrage** [comment]
Sorry, I don't really understand. Can you explain further please?
