### ISSUE TITLE
Troubleshooting: Form submit is not displaying success or adding record

### ISSUE THREAD

**Issue by github-ptaylor** [skydiver/october-plugin-forms#197]
Hello Martin aka Skydiver ;)

My form submissions are not generating a success message and the submissions are not being inserted in the database.

The URL of the contact form:

https://imarketstuff.com/contact-us

Upon submitting the form, the URL shows the submitted parameters plus the token (the submit parameter is empty):

i.e.

https://imarketstuff.com/contact-us?_token=ECyuIsRe6QaJhGk0638rVgwsaN5O49boTq1HMeVP&name=Patrick+C.+Taylor&email=greenoutreach%40myemail.com&message=This+is+a+test+message&submit=

If you can provide any direction into troubleshooting this, that would be great.

I have attached my component configuration screen also.

Thanks for your time

![Screen Shot 2020-05-18 at 07 20 27](https://user-images.githubusercontent.com/13399385/82217825-36532d00-98d8-11ea-8be8-3160e9e56437.png)

**Comment by mjauvin** [comment]
@github-ptaylor you have javascript error on this page, which prevents the ajax framework from properly submitting the form using ajax.

Check your browser javascript debug console for more info.

**Comment by github-ptaylor** [comment]
Thanks Mark!

I will check that out.

**Comment by github-ptaylor** [comment]
update:

the issues was caused by having a "slim" version of the JQuery library in the code base, the "slim" version doesn't have the $.ajax function.

thanks again Mark for the pointer in the right direction :)
