### ISSUE TITLE
Auto-response email and admin mail notifications are not delivered

### ISSUE THREAD

**Issue by ghost** [skydiver/october-plugin-forms#199]
Hi and thank you for this amazing plugin!

i'm using **genericForm** and when i submit an email from email form  (in localhost using SMTP) i don't receive auto-response email nor email notifications, i tried to send a test message through **Mail templates** and it worked without any issues, what am i missing?

**Comment by rangrage** [comment]
Hi Martin @skydiver, 

I am having the same issue on one of my sites, this was working all along but recently it has been brought to my attention that the autoresponse messages are not being sent. I've checked error logs but nothing. When I test from backend->settings it sends fine. So, not sure what else to check. 

Thanks for your help.

**Comment by spanjaan** [comment]
![Capture](https://user-images.githubusercontent.com/64153858/138634533-6489c0bd-259a-47fe-923a-5f14ced7992f.JPG)
hi,
how to add auto response email field??
please help me.
