### ISSUE TITLE
DB error

### ISSUE THREAD

**Issue by martinBadin** [skydiver/october-plugin-forms#2]
Hi,

I have issue with different columns in DB. The column has name `form_data` but in your code has name `form_data_arr`.

> SQLSTATE[42S22]: Column not found: 1054 Unknown column 'form_data_arr' in 'order clause' (SQL: select `martin_forms_records`.* from `martin_forms_records` where `martin_forms_records`.`deleted_at` is null order by `form_data_arr` desc limit 20 offset 0)

**Comment by skydiver** [comment]
Fixed.
Will be available for update in a few hours.
