### ISSUE TITLE
recaptcha setting on multiple forms

### ISSUE THREAD

**Issue by nolyboms** [skydiver/october-plugin-forms#200]
I have two forms on my page with different recaptcha settings.

"recaptcha_enabled: 0" & on the second one "recaptcha_enabled: 1"

The setting of the second one overrides the first on the page since the first one gets hided only if setting of the second one is set to 0.

**Comment by skydiver** [comment]
Hello @nolyboms 

As i understand, you have 2 forms on the same page, one uses recaptcha, the other doesn't
