### ISSUE TITLE
Allow "/" and other potential RegEx characters in field names

### ISSUE THREAD

**Issue by developerabdd** [skydiver/october-plugin-forms#201]
Hello,

I've come across a simple case where, upon using the custom_attributes[] option of the forms, a form attribute name had a "/" character, which caused an error in `martin/forms/classes/BackendHelpers.php:81` "unrecognized modifier 'C'". The field name was "Nº BI/CC", which broke the code used in the line I mentioned.

I have Martin.Forms v1.4.20 and the original line code was:
```php
$pattern = '/{{\s*('.$pattern.')\s*}}/';
```
which needed only be changed to:
```php
$pattern = '/{{\s*(' . preg_quote($pattern, '/') . ')\s*}}/';
```

I hope this hasn't already been filed as an issue; I couldn't find it if it has.

Cheers from Portugal,
David @ Adhesive / Brand+Digital Designers

**Comment by skydiver** [comment]
Hello @developerabdd 

I wasn't able to replicate your error.

I've used this form:

```
<form data-request="{{ __SELF__ }}::onFormSubmit">
    {{ form_token() }}
    <div>
        <input type="text" name="name">
    </div>
    <div>
        <input type="text" name="Nº BI/CC">
    </div>
    <button>submit</button>
</form>
```

and i'm able to store the data without problems:

![image](https://user-images.githubusercontent.com/578784/89488041-57137c00-d77d-11ea-8285-5d6a51e6cc8b.png)

can you give me more info?

Thanks.-

**Comment by developerabdd** [comment]
Hello @skydiver, thanks for replying.

Did you use a custom attribute name like I mentioned? Like so:

```
[genericForm]

...

custom_attributes[nr_bi_cc] = "Nº BI/CC"

...

        <input type="text" name="nr_bi_cc">

```

The only other thing I can think of is maybe the PHP version, which was 7.1 when I opened this issue. We've since upgraded to PHP 7.3 and kept the fix I proposed in place.

**Comment by skydiver** [comment]
(was looking for old/unresolved issues)

still can't replicate, this is my component config:

```
[genericForm]
custom_attributes[nr_bi_cc] = "Nº BI/CC"
messages_success = "Your form was successfully submitted"
messages_errors = "There were errors with your submission"
reset_form = 1
inline_errors = "disabled"
sanitize_data = "disabled"
anonymize_ip = "full"
recaptcha_theme = "light"
recaptcha_type = "image"
recaptcha_size = "normal"
emails_date_format = "Y-m-d"
```

and this is the form:

```
<form data-request="{{ __SELF__ }}::onFormSubmit">
    {{ form_token() }}
    <div>
        <input type="text" name="name">
    </div>
    <div>
        <input type="text" name="nr_bi_cc">
    </div>
    <button>submit</button>
</form>
```

feel free to reopen the issue and upload a zip with the broken form
