### ISSUE TITLE
Problem with old rules still active

### ISSUE THREAD

**Issue by kevingrevillot** [skydiver/october-plugin-forms#204]
Hello, I've got a problem with setting up my contact form with magic forms on October CMS. A week ago I did a test on configuring a simple contact form for my client's website. I set some basic rules and I set mail sender using Gmail Mailer Driver plugin. All worked perfectly then.

I now have to set a more complex contact form with more fields, some radio buttons etc... So I deleted old rules and created new ones in my contact partial. The problem I have is that the new rules I set are not applying but the old ones are. But I have no clue where these "ghost" old rules are stored.

I set all my rules and rules messages in the "Generic AJAX Form" control box inside of my contact form partial

Do you have any idea where could the old rules be stored and how to delete them ?

**Comment by skydiver** [comment]
Hello @kevingrevillot 

I believe this is related to https://github.com/skydiver/october-plugin-forms/issues/203

**Comment by kevingrevillot** [comment]
> Hello @kevingrevillot
> 
> I believe this is related to #203

Hello,

thanks for your answer

Unfortunately I ran the 468 update and then ran php `artisan october:util compile js` but I didn't fix my problem

It did fix the #203 problem ([see here](https://gyazo.com/ec74e12c20a433bab089b3623d5edea7)) but it didn't fix mine

Here you can see the rules I set : https://gyazo.com/5c9d2d318e289692229794abaf7beafb
But here is the rules messages I get in front : https://gyazo.com/014eafdb039616ec5fbfa70514151b84

These are some old rules I've deleted a while ago, and the new rules I set are not taken into account
