### ISSUE TITLE
Modal BCC error

### ISSUE THREAD

**Issue by raelcv** [skydiver/october-plugin-forms#207]
Problem with modal in BCC recipients after update for build 467

![image](https://user-images.githubusercontent.com/20374761/90455078-6377cd00-e0cb-11ea-9af4-82b4a7b265a3.png)

**Comment by Guvanchhojamov** [comment]
I have same problem. I can't delete the code and add my Email address on  Recipients. Help me if you know solution??!

**Comment by Guvanchhojamov** [comment]
![oct_err](https://user-images.githubusercontent.com/43471352/90489681-0a557b00-e157-11ea-8f4d-fe9966dc5a04.png)

Screenshot

**Comment by raelcv** [comment]
^ Only the modal is in error. You can edit the htm file in the themes folder.
[emptyForm]
...
mail_enabled = 1
mail_subject = "Contact Form"
mail_recipients[] = "contact@mail.com"
mail_recipients[] = "contact2@another.com"
mail_bcc[] = "me@myemail.com"
mail_replyto = "email"
...

**Comment by skydiver** [comment]
Hello @raelcv and @Guvanchhojamov 

This is an existing OctoberCMS bug, you can read more about the issue here: https://github.com/skydiver/october-plugin-forms/issues/203
