### ISSUE TITLE
Add Recipients Error. On version 1.4.20

### ISSUE THREAD

**Issue by Guvanchhojamov** [skydiver/october-plugin-forms#208]
I want add Recipients (Email address) to my form.  And the Recipients textarea is not  empty. See on belov screenshot
 .  I cant delete that code from textarea. Help me please how can I solve this problem. Thank you a lot 

![err1](https://user-images.githubusercontent.com/43471352/90490007-8780f000-e157-11ea-9b31-4aeaf71c2b2b.png)

**Comment by skydiver** [comment]
Hello @Guvanchhojamov 

This is an existing OctoberCMS bug, you can find more info here: https://github.com/skydiver/october-plugin-forms/issues/203

**Comment by Guvanchhojamov** [comment]
Thanks for the answer. I will try the suggested options, or we will wait for the October CMS update. If there is news please let me know. Thanks for your work. Good luck to you.

**Comment by Guvanchhojamov** [comment]
Thank you. This solved my problem

I run `php artisan october:util compile js`

In my case this helped me! Good luck!
