### ISSUE TITLE
Load recaptcha async or when form is clicked

### ISSUE THREAD

**Issue by johrclaessens** [skydiver/october-plugin-forms#209]
The recaptcha library impacts page loading times a lot. This could be fixed by dynamically loading the script once the user clicks on the form or simply after the page is loaded to prevent long page loading times.

It also should have a toggle in the settings for pages who run in trouble when using this method.

**Comment by skydiver** [comment]
Hey @johrclaessens 

You can copy `components/partials/recaptcha.htm` to your theme and modify, maybe add some javascript listener to load the recaptcha code when you need it.
