### ISSUE TITLE
Inline error message

### ISSUE THREAD

**Issue by Zmove** [skydiver/october-plugin-forms#21]
Hello,

It would be great to have an option to display error messages just before or just next the field instead of global message in the top of the form.

Just an idea to improve this plugin that is already really great !

Alex

**Comment by jajacobs** [comment]
Hi, remove your customer error display logic and leave it the ajax framework. https://octobercms.com/docs/ajax/extras

**Comment by skydiver** [comment]
I was working on the suggestion by @jajacobs and works fine except por recaptcha validation.

Another idea in #35 is to pass a variable with the errors and add some custom javascript to mark the fields.

**Comment by skydiver** [comment]
@Zmove or @jajacobs, can you test the branch "inline-errors" ?

There is a variable is in the response and javascript marks the errors fields ...

This is a demo code i was testing
```
<form data-request="{{ __SELF__ }}::onFormSubmit" data-request-validate data-request-flash>

    {{ form_token() }}

    <div id="{{ __SELF__ }}_forms_flash"></div>

    <div class="form-group">
        <label for="name">Name:</label>
        <input type="text" id="name" name="name" class="form-control">
        <div data-validate-for="name"></div>
    </div>

    <div class="form-group">
        <label for="email">Email:</label>
        <input type="text" id="email" name="email" class="form-control">
        <div data-validate-for="email"></div>
    </div>

    <div class="form-group">
        <label for="subject">Subject:</label>
        <input type="text" id="subject" name="subject" class="form-control">
    </div>

    <div class="form-group">
        <textarea id="comments" name="comments" rows="8" cols="80"></textarea>
    </div>

    <button id="simpleContactSubmitButton" type="submit" class="btn btn-default">Submit</button>

</form>
```

Thanks.-

**Comment by jajacobs** [comment]
Why don't you put <span data-validate-for="g-recaptcha-response"></span> under {% partial '@recaptcha' %} ?

<div class="form-group">
        {% partial '@recaptcha' %}
        <span data-validate-for="g-recaptcha-response"></span>
</div>

**Comment by skydiver** [comment]
The BETA branch has the inline functionality.
Anyone wants to test before release?

Thanks.-

**Comment by skydiver** [comment]
Inline errors was release in version 1.3.7

**Comment by Alex360hd** [comment]
Small question that refer to [that issue](https://github.com/skydiver/october-plugin-forms/issues/20) that was merged with this one.

How do you add an "has-error" class to element that does not validate ?

I red the documentation, was able to display the error message in a div under the field, but I don't see how can I add an error class to the parent div of the field that don't validate.

Thanks for the help
