### ISSUE TITLE
Plugin breaks in Build >1.0.469

### ISSUE THREAD

**Issue by LukeTowers** [skydiver/october-plugin-forms#213]
Because this plugin abuses an unsupported bug in older October builds (loading JS files as partials) that was blocked for security reasons in Build v1.0.469 and onwards (and never should have been present in the first place) this plugin breaks on newer builds of October. See https://github.com/octobercms/october/issues/5272.

The problematic code is here: https://github.com/skydiver/october-plugin-forms/blob/f3fe2feca89712a7be2c4758c4e5c12d39c0369b/classes/MagicForm.php#L278-L283

**Comment by PubliAlex** [comment]
Is there a way for a quick and dirty fix ? cause I have some production website that are stuck because of this actually...

**Comment by LukeTowers** [comment]
@PubliAlex very very dirty quick fix is the following, DO NOT KEEP AROUND IN PRODUCTION, THIS CODE IS NOT GUARANTEED TO CONTINUE WORKING:
```php
\Cms\Classes\Partial::extend(function($model) {
   $model['allowedExtensions'] = ['htm', 'js'];
});
```

**Comment by skydiver** [comment]
Thanks for the help, this will be release on v1.5.0 https://github.com/skydiver/october-plugin-forms/pull/216

**Comment by Kusdrae** [comment]
is there any real solution to this problem ? i cannot resolve it in my project

**Comment by LukeTowers** [comment]
@Kusdrae you should just be able to update the plugin.
