### ISSUE TITLE
Error for Partial Recaptcha

### ISSUE THREAD

**Issue by worldofsmarty** [skydiver/october-plugin-forms#22]
An error occurs when i enable recaptcha in settings of generic forms or Empty Form and in case of generic forms when i expand the component. It throws this below error. May i know how to resolve the error. 

An exception has been thrown during the rendering of a template ("The partial 'recaptcha' is not found.").

TYPE

Twig Template

EXCEPTION

Cms\Classes\CmsException

  
            <div class="form-group">
                <textarea id="comments" name="comments" rows="8" cols="80"></textarea>
            </div>
  
            {% partial '@recaptcha' %}
            <button id="simpleContactSubmitButton" type="submit" class="btn btn-default">Submit</button>

**Comment by skydiver** [comment]
Hello @worldofsmarty 

I wasn't able to reproduce the error, can you give me more details on this?


Thanks.-

**Comment by worldofsmarty** [comment]
I have shown the error i am getting. It is on both localhost and on the live website both of them i am getting the same thing.

![error](https://cloud.githubusercontent.com/assets/5152491/22402050/ecf46216-e60e-11e6-9991-246c02d0e7a7.jpg)

**Comment by worldofsmarty** [comment]
Kindly let me know if i am doing anything wrong. This is happening even when i expand the Empty Form Component.

**Comment by skydiver** [comment]
You need to override the component partial [(more info)](https://octobercms.com/docs/cms/components#overriding-partials)

Create a partial "genericForm/default.htm" and paste your code.
