### ISSUE TITLE
Image/file validation error

### ISSUE THREAD

**Issue by zakir1929** [skydiver/october-plugin-forms#227]
#Image/file validation is not working. 

Steps for recreating the issue.

=> Use any component of your plugin (i.e. genericForm)
=> just add a ``` <input type="file"> ``` field in a HTML form for image upload
=> add a required and image rule in component ``` required|image ```
=> submit the form

it won't work

after digging a lot. I see that you have used ```post()``` function inside the magicForm.php class for retrieving form data.

The ``` post() ``` function won't accept image input and it is just there for accepting post input. 
So to fix that I have created a PR. please accept it and add it to your new version.

Thanks

**Comment by zakir1929** [comment]
#226

**Comment by afdstudio** [comment]
Hi! I saw your post and I have a doubt related to it...
How can I make file upload required on a Form within magic forms plugin?
Any help will be very welcome!
Thank you in advance!
