### ISSUE TITLE
reCAPTCHA does not work

### ISSUE THREAD

**Issue by SciCrea** [skydiver/october-plugin-forms#228]
Build 1.0.471
Martin.Forms 1.5.1

Hello, reCAPTCHA does not work. The flag is not displayed, although the form when the submission makes an error that "The reCAPTCHA field is required" I tried the alternative plugin reCAPTCHA Multiwebinc.Recaptcha - it worked.

**Comment by siddharth** [comment]
Try including the included recaptcha.js in the plugin and Google's recaptcha js. These are not included by default when you enable recaptcha and need to be manually added to the layout.
