### ISSUE TITLE
Expected response code 250 but got code 550

### ISSUE THREAD

**Issue by abishekh07** [skydiver/october-plugin-forms#241]
I tried using Magic Forms on one of my webpages. I get the following error:

"Expected response code 220 but got code 550, with message 550 5.7.1 relaying denied " on line 456 of /var/www/vhosts/hostname.nl/httpdocs/cms/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/AbstractSmtpTransport.php
"

Is this a mistake on my part. I am totally new to October CMS.

**Comment by Ana-Maria95** [comment]
I don't know if it helps, but I got that when my server (mailtrap for development purposes), wasn't set right. So maybe that is the issue?

**Comment by abishekh07** [comment]
It certainly is a server issue, judging by the code 550. However, October CMS is too confusing and I am struggling with this for the past 4 days.

**Comment by Ana-Maria95** [comment]
I don't know, that happened to me recently and it was the mail **configuration** problem for me, not the server. I didn't get my settings right at first. Check if your Mai method, SMTP port, an SMTP encryption protocol, Username, and Password are correct in Settings->Mail configuration, that helped me. Either way, good luck!
