### ISSUE TITLE
How to add auto response email field in generic forms?

### ISSUE THREAD

**Issue by spanjaan** [skydiver/october-plugin-forms#262]
![Capture](https://user-images.githubusercontent.com/64153858/138634336-64fca766-7063-489d-86d0-590af10a92d3.JPG)
how to add auto response email field in generic forms??

**Comment by SplicedWeb** [comment]
Hi Anjaan2077,

In the Email field, just enter the input name that you used in your form for email.
If your input on the form code looks like this:
`<input` name="email_address" type="email">

you would just write email_address in that field.
Then populate your sender address and the subject.  Mail template can be left blank or enter as you find it in /backend/system/mailtemplates

so for example, that could read: martin.forms::enquiry.autoreply (which is the default that is applied if you don't create a new template)

**Comment by spanjaan** [comment]
Thank you so much..

**Comment by spanjaan** [comment]
> Hi Anjaan2077,
> 
> In the Email field, just enter the input name that you used in your form for email. If your input on the form code looks like this: `<input` name="email_address" type="email">
> 
> you would just write email_address in that field. Then populate your sender address and the subject. Mail template can be left blank or enter as you find it in /backend/system/mailtemplates
> 
> so for example, that could read: martin.forms::enquiry.autoreply (which is the default that is applied if you don't create a new template)
