### ISSUE TITLE
Using Magic Form on October CMS 3

### ISSUE THREAD

**Issue by MateThemes** [skydiver/october-plugin-forms#266]
Hello,

I installed Magic Form on October CMS 3. When I want to send a test form I got this message:

`"Email "0" does not comply with addr-spec of RFC 2822." on line 54 of /Users/.../vendor/symfony/mime/Address.php

What does this error mean?

**Comment by skydiver** [comment]
Plugin is not under development anymore.
You can read more here: https://github.com/skydiver/october-plugin-forms/discussions/267

Thanks.-

**Comment by cdiktakis** [comment]
I'm getting the same error...

**Comment by webBook-cz** [comment]
I found a solution:
Change function sendTo to send
classes/SendMail.php
line 59:
            Mail::send($template, $data, function($message) use ($properties, $post, $files) {
                   $message->to($properties['mail_recipients']);
