### ISSUE TITLE
Multi checkbox – correct way to group checkboxes ?

### ISSUE THREAD

**Issue by damsfx** [skydiver/october-plugin-forms#29]
Thank's for this great plugin.

I did not find in the documentation how to use the multiple checkbox field ?

Whith this code 
```
 <input type="checkbox" name="chk_group" value="value1" />Value 1<br />  
 <input type="checkbox" name="chk_group" value="value2" />Value 2<br />  
 <input type="checkbox" name="chk_group" value="value3" />Value 3<br />
```
the plugin store only the last checked checkbox value.

I need to use : 
```
<input type="checkbox" name="chk_group[]" value="value1" />Value 1<br />
<input type="checkbox" name="chk_group[]" value="value2" />Value 2<br />
<input type="checkbox" name="chk_group[]" value="value3" />Value 3<br />
```
in order to get grouped values.
**chk_group** : _Value 1, Value 2 ... _

This can be retrieved in PHP with a simple loop:
```
<?php
if (isset($_POST['chk_group'])) {
    $optionArray = $_POST['chk_group'];
    for ($i=0; $i<count($optionArray); $i++) {
        echo $optionArray[$i]."<br />";
    }
}
?>
```

Is there a way to get this working in Magic Forms ?

**Comment by skydiver** [comment]
Hello @damsfx 

Using
```
<input type="checkbox" name="chk_group[]" value="value1" />Value 1<br />
<input type="checkbox" name="chk_group[]" value="value2" />Value 2<br />
<input type="checkbox" name="chk_group[]" value="value3" />Value 3<br />
```
the values are stored on the database but the record details page throw an error.

I'm fixing this page to display a list with the values, but i think the only way to get this data is to name the fields like `chk_group[]`

**Comment by damsfx** [comment]
Hi @skydiver

Yes, I've take look at the DB and see that only the details page wait for a string when an array is used.

And yes, it's the only known HTML method to get group values in forms treatment.

Thanks again for your time.

**Comment by skydiver** [comment]
Record detail page was fixed

Thanks @damsfx for the report

**Comment by damsfx** [comment]
Can't get it working ...

`"An exception has been thrown during the rendering of a template ("nl2br() expects parameter 1 to be string, array given") ...`

Any ideas ?

**Comment by skydiver** [comment]
@damsfx have you updated to version 1.3.3?

**Comment by damsfx** [comment]
Yes ...
Of course.

Showing form is ok, submitting too.
DB update look fine but Ajax function return the error.

I didn't have the problem with previous version.
Will try with a fresh site.


Le 18 févr. 2017 01:08, "Martin M." <notifications@github.com> a écrit :

@damsfx <https://github.com/damsfx> have you updated to version 1.3.3?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/skydiver/october-plugin-forms/issues/29#issuecomment-280800784>,
or mute the thread

**Comment by skydiver** [comment]
> Yes ...
> Of course.

Sorry for asking @damsfx ...

**Comment by skydiver** [comment]
Hello @damsfx, the problem is still there?

Thanks.-

**Comment by damsfx** [comment]
Hi,

Yes problem still there.
The origin of the error seems to lie when adding these 2 lines
````
    {{ form_token() }}
    <div id="{{ ContactForm }}_forms_flash"></div>
`````

This form work :
````
<form data-request="{{ ContactForm }}::onFormSubmit">
	<input type="checkbox" name="color[]" id="checkbox-1" value="red"   />Red
	<input type="checkbox" name="color[]" id="checkbox-2" value="blue"  />Blue
	<input type="checkbox" name="color[]" id="checkbox-3" value="green" />Green

	<input class="btn btn-success" value="Envoyer" type="submit" required>
</form>
````

This not :
````
<form data-request="{{ ContactForm }}::onFormSubmit">
	{{ form_token() }}
	<div id="{{ ContactForm }}_forms_flash"></div>

	<input type="checkbox" name="color[]" id="checkbox-1" value="red"   />Red
	<input type="checkbox" name="color[]" id="checkbox-2" value="blue"  />Blue
	<input type="checkbox" name="color[]" id="checkbox-3" value="green" />Green

	<input class="btn btn-success" value="Envoyer" type="submit" required>
</form>
````

**Comment by rangrage** [comment]
Im still having this problem using v.1.4.4.1
