### ISSUE TITLE
Redirect / Succes page

### ISSUE THREAD

**Issue by WLepelaar** [skydiver/october-plugin-forms#34]
Is it possible to redirect to a specific "thank you" page when a form is succesvol submitted?

**Comment by Alex360hd** [comment]
I don't think it's possible by default at the moment.

I could do it with a hackish solution but it works :

    $('#myform').ajaxComplete(function () {
      if (!form.find('.alert-error').length) {
        window.location.href = "/thanks";
      }
    });

Basically it trigger on ajax complete event and check if there is an error message on the form. If not we suppose the form submission is a success and so we go to the page you want

But it would be great to add an option to do that without using hackish solution like mine. So +1 for the feature

**Comment by skydiver** [comment]
There is a new option to redirect on success.

![screenshot from 2017-03-01 22-32-42](https://cloud.githubusercontent.com/assets/578784/23489039/028e29a8-fecf-11e6-8326-e92a0ef9e87b.png)

Will be available in the next release

**Comment by WLepelaar** [comment]
**Great job!** Thank you!

Can you tell me when the next release will be?
