### ISSUE TITLE
Add variable to flash.htm partial to get the name of all fields giving an error

### ISSUE THREAD

**Issue by Alex360hd** [skydiver/october-plugin-forms#35]
Hello,

I'm trying to customize the flash error message, and I think it would be great to have a variable (an array) that give the name of all fields that returned an error.

Like that, I could write some JS to add an "has-error" class to fields that returned an error and make a better UI with fields outlined in red when there is a problem.

A nice way to do that would be to consider the key of the {{ list }} twig tag as the field name, like that we can have the name of the field and the associated error message.

**Comment by skydiver** [comment]
This is related to #21 

There is an "automatic" october way ... 

Will be available in the next version
