### ISSUE TITLE
Uncaught TypeError: $(...).render is not a function

### ISSUE THREAD

**Issue by Alex360hd** [skydiver/october-plugin-forms#37]
Hello,

I tried the file upload form, no customization at the moment, regular component, called using, just activated the upload feature.

    {% component 'uploadForm' %}

But when I go to my form, I have the following error

    Uncaught TypeError: $(...).render is not a function
        at uploader.js:340
        at uploader.js:344

Did I miss something ?

Here is my component code

    [uploadForm]
    messages_success = "Sent"
    messages_errors = "Errors"
    recaptcha_enabled = 0
    recaptcha_theme = "light"
    recaptcha_type = "image"
    recaptcha_size = "normal"
    uploader_enable = 1
    uploader_multi = 0
    placeholderText = "Click or drag files to upload"
    maxSize = 5
    fileTypes[] = "jpg"
    fileTypes[] = "jpeg"
    fileTypes[] = "pdf"

Regards,

Alex

**Comment by skydiver** [comment]
Probably you have:

```
{% scripts %}
{% framework extras %}
```

instead of:
```
{% framework extras %}
{% scripts %}
```

On your layout ...

**Comment by Alex360hd** [comment]
You are right, I loaded the framework extra before the script tags, but I added a defer on framework extras and so, it was loaded after others scripts.

Removing the defer fixed the problem
