### ISSUE TITLE
Upload required

### ISSUE THREAD

**Issue by ghost** [skydiver/october-plugin-forms#42]
Hello,

I wonder how to define upload as required. For others fields you can use validation rules with the field name, but the upload field don't have any names, so how to make it required ?

Regards,

**Comment by skydiver** [comment]
Not sure if there is possible right now (i will take a look).

Maybe is time to start thinking on another upload component...

**Comment by jaycbrf4** [comment]
http://blueimp.github.io/jQuery-File-Upload/index.html

**Comment by Zmove** [comment]
+1 for the plugin linked above. Very good plugin that may help for a better integration of upload system to magicform.

**Comment by Alex360hd** [comment]
Hello,

Any update with this ? I don't have enought october cms skill (yet) to help, but the jquery file upload solution linked above could be a very good solution.

**Comment by skydiver** [comment]
Hello @Alex360hd, i made a few test some time ago (unfortunately don't have to much free time).

Using the plugin it's easy, the difficult part is the integration with [October attachments](https://octobercms.com/docs/database/attachments) and saving the files before submit the form.

The current upload was easy because there was already a plugin doing all this task.

I'm interested on this issue, but as i say, don't have free time right now :disappointed:

**Comment by Zmove** [comment]
Hello,

Do you have an edge version of the module with the integration with the jquery file upload plugin ? To clearly see what's missing with october attachments to make it works.

**Comment by skydiver** [comment]
@Zmove don't have any code, i've deleted my tests because was useless, sorry

**Comment by TonnnnUK** [comment]
For anyone coming across this issue a hacky way around this I have implemented is by adding a session within the checkUploadAction function in ComponentUtils.php in the traits folder. This triggers and adds the session when a file is uploaded.

Within MagicForm.php in the onFormSubmit method check if _uploader is set. If isset then check for the file uploaded session created above. If it's not found add to the $rules and $msgs variables to output the validation message.

If you may multiple forms and some might not require the file upload you may need to add a hidden field which can be checked if isset along with the _uploader field.

Finally add the Session::forget() method when the record is saved to the database and within the onRemoveAttachment method in the fileuploader.php file (incase a user removes the file and forgets to add another).

Hope this helps.

**Comment by afdstudio** [comment]
Hi! I saw this post and I have the same need...
How can I make file upload required on a Form within magic forms plugin?
Any help will be very welcome!

@TonnnnUK gave a great solution but I don't know how to implement...

If anyone have a simplest way, it will be fine!
Thank you in advance!
