### ISSUE TITLE
Asking the Basic

### ISSUE THREAD

**Issue by Amn37ia** [skydiver/october-plugin-forms#46]
hello... i have question about the basic that i dont know, just like the user plugin when i want to add the submit value to the front-end i must add something like {{user.name}}, but i've confused when using the value from the form i build, to show up in front-end page, is that i must  using sql query to echoing the value?

Q : how to use the value from the back-end table to front-end page.

Thanks.

**Comment by skydiver** [comment]
The data is stored as json on the "form_data" field.

You can convert to a php array with json_decode().

(I will add something to the docs)

**Comment by Amn37ia** [comment]
thanks it's very useful but how to get RECORD_ID? or just ID of the index record?
