### ISSUE TITLE
Make different table for each form

### ISSUE THREAD

**Issue by SchneiderDe** [skydiver/october-plugin-forms#5]
Hello,

Currently, the configuration of fields is saved in a table, in one field and generates as "stored fields". 
This is, thus, restrictive because one cannot map it to other tables or other plugins cannot work with it.

Instead of saving the field configuration, how about creating a real table for that particular form?

Then one could have the name as suffix, for e.g. martin_forms_myNameOne, martin_forms_myNameTwo, etc. This should not be a problem with Migration of tables.

With this, all the fields are real and mapped, not like now. Then other plugins could use and interface with the form fields.

For e.g.:

martin_forms_myNameOne ---> Dating profile
martin_forms_myNameTwo ---> Business Profile

etc. This feature would be fantastic to have.

**Comment by skydiver** [comment]
The problem with multiple tables (apart from a cluttered database) is that any modifications to the form requires modify the tables.

If you need to work with the stored data, you can convert the "form_data" field (it's json) to php array.

I understand you cannot join tables but database management fall outside the scope of the plugin.

**Comment by SchneiderDe** [comment]
> but database management fall outside the scope of the plugin.
Thanks.
Thus, I close this thread.
