### ISSUE TITLE
How to add Front End Form Record Editor

### ISSUE THREAD

**Issue by Amn37ia** [skydiver/october-plugin-forms#50]
okay i've problem while creating front end record data for specific form, i want add data's editor and it's failed data did'nt change at all, im using same name form but different in page.

how can i possibly change the record in front end, and btw please give record data editor in front / back end.

Thanks, your plugin is awesome.

**Comment by skydiver** [comment]
Right now edit records is not on the plans.
If anybody want to send a PR will be welcome.
