### ISSUE TITLE
Custom submission handler?

### ISSUE THREAD

**Issue by BenWoodford** [skydiver/october-plugin-forms#51]
Imagine a scenario where I don't want to save it to a DB or send an email but rather handle it in a custom way. Does this plugin support that? Basically I want to submit tickets to Zendesk directly via their API (can't send on behalf of another user very easily with Amazon SES)

**Comment by skydiver** [comment]
Sounds interesting.

I imagine the custom handler needs to run on page level and after all the validation, the component needs to call to the page.

Not sure if it's possible, but i will take a look.

**Comment by skydiver** [comment]
Hello @BenWoodford 

Since version 1.4.0 the plugin includes a few events.

You can capture the data and do whatever you want.

Check the docs for info.
