### ISSUE TITLE
Flash Messages on long forms

### ISSUE THREAD

**Issue by rangrage** [skydiver/october-plugin-forms#54]
Hi, 

I am building some very long forms, and when the form is submitted the flash messages are displayed way at the top and the user has no idea if there were any errors with the submission, unless they scroll back to the top of the page. 

Is there a way to scroll to the position of the flash messages once the form is submitted? 

Thanks,

**Comment by rangrage** [comment]
I've re-positioned the flash messages at the bottom of the form.

**Comment by skydiver** [comment]
Ver. 1.3.9 includes a new option to execute custom JavaScript code on form success / error.

On this particular case, you can add some code to scroll to top.

**Comment by qroft** [comment]
@rangrage could you show here the partal layout that you have created? I am also getting the flash to work, but am totally unable to loop and show the errors in it. thanks in advance!
