### ISSUE TITLE
Undefined index: mail_template

### ISSUE THREAD

**Issue by rangrage** [skydiver/october-plugin-forms#58]
Hi, 

After the latest update I am receiving this error when submitting forms. 

I have not check the 'Send Auto-Response' option in my component and it is giving an alert message with this error when submitting the form. 

I then added the default mail template for the auto-response but it's still giving the same error. How can I fix this? 

Thanks for your kind assistance.

**Comment by rangrage** [comment]
I've updated from the git repo, so after doing artisan october:up it's all working fine now.

**Comment by rangrage** [comment]
`"Undefined index: mail_template" on line 15 of \testsite\plugins\martin\forms\classes\SendMail.php"`

**Comment by skydiver** [comment]
Fixed.
Thanks.-
