### ISSUE TITLE
Magic Forms: Issue

### ISSUE THREAD

**Issue by ashok2009it** [skydiver/october-plugin-forms#59]
How to fix this issue ?

"Array to string conversion" on line 179 of /var/www/html/octcms.dev/vendor/laravel/framework/src/Illuminate/Support/MessageBag.php
![screenshot from 2017-05-24 15-23-37](https://cloud.githubusercontent.com/assets/11731004/26397137/068b229c-4095-11e7-9079-26f4b4104ab8.png)
![screenshot from 2017-05-24 15-25-00](https://cloud.githubusercontent.com/assets/11731004/26397194/2fde9bba-4095-11e7-946f-ad41b88337a6.png)

**Comment by skydiver** [comment]
Hello @ashok2009it, can you post your form code?

Thanks.-
