### ISSUE TITLE
custom Email subject

### ISSUE THREAD

**Issue by markandmedia** [skydiver/october-plugin-forms#6]
Is there a way to overwrite the default subject? I can do this in the mail view of your plugin, but that off course will be over-written with future updates

**Comment by skydiver** [comment]
You can change the subject on the email template.
Once created, (i think) it's not modified with every upgrade.

Don't know if it's possible to configure the template subject from the component (i will take a look).

**Comment by markandmedia** [comment]
Thank you for the quick reply. You plugin works like a charm!
