### ISSUE TITLE
Reply-To option

### ISSUE THREAD

**Issue by Alex360hd** [skydiver/october-plugin-forms#60]
Hello,

It's very useful to be able to add a Reply-To option in a form to allow replying to your visitors using the reply function of your webmail.

Is it possible to add an option the plugin component to be able to define the Reply-To option, you should be able to target a field of the form cause generally, you have to reply to the email address filled in the form.

Thanks

**Comment by skydiver** [comment]
Hello @Alex360hd.

Are you referring to the notification or auto-response email?

**Comment by Alex360hd** [comment]
I'm referring to the notification system. I don't want to send an auto-response email, but I want that my customer be able to answer to a question sent with a magic form by using the reply button of their webmail.

It's also a good idea to avoid spam, as you have less chance to be in spam is this is the website that is the sender of the mail, that's why the reply-to option exists.

**Comment by Alex360hd** [comment]
Hello,

I added the feature, but I'm new to git and I don't know how to create a pull request yet, so I will post the solution "the old way" !

[Here is my SharedProperties.php](https://pastebin.com/TH0Mh7WV) that add the option in the component and the [SendMail.php](https://pastebin.com/dBuuTVAe) that take care of this new option when sending a notification.

If somebody can easily create a patch or something easy for the author to integrate, I promise to learn how to make a proper patch later, but no time ATM ^^

**Comment by skydiver** [comment]
Thanks for your code @Alex360hd 

This is ready on v1.4.1

I will wait a few days before pushing to October market, meanwhile you can test with the master branch

**Comment by Alex360hd** [comment]
Thanks, seems to work well.

**Comment by worldofsmarty** [comment]
Well when can we expect it to be pushed to the october market place...!!!

**Comment by Alex360hd** [comment]
I recently saw the changelog when I updated my october install, I think it's already implemented.

**Comment by worldofsmarty** [comment]
Thank you for the same.

**Comment by Alex360hd** [comment]
Yes, you have to fill the "name" attribute of your field. Some example :
