### ISSUE TITLE
Values of the Forms Submitted

### ISSUE THREAD

**Issue by worldofsmarty** [skydiver/october-plugin-forms#61]
Can we see the stored values of the forms in the form list.

**Comment by skydiver** [comment]
Hello @worldofsmarty.

The problem with this feature is what happen when too much information are stored per record.

What is your idea on this cases?

**Comment by worldofsmarty** [comment]
Ohh Ok i get it... It just came to my mind that if we can see atleast from which email or name of the sender who has submitted the form... That was my idea... But i totally agree that it will be too much information to be shown in case of many fields... We can close this issue.. Thanks for the reply... Awesome Plugin.
