### ISSUE TITLE
Validation failed on array with checkboxes

### ISSUE THREAD

**Issue by tschmidleithner** [skydiver/october-plugin-forms#62]
Hello,

first, thank you for contributing this useful plugin.

With the latest OctoberCMS (build 419) and MagicForms (1.3.9) plugin I ran into a problem with a form containing checkboxes.

The form looks like this (simplyfied):
```html
<form data-request="{{ genericForm }}::onFormSubmit">
    {{ form_token() }}
    <label><input class="form-check-input" type="checkbox" name="Product[]" value="Product1">Product 1</label>
    <label><input class="form-check-input" type="checkbox" name="Product[]" value="Product2">Product 2</label>
</form>
```

However, even if I don't specify any validation rules, I am running into a **406 Not Acceptable** HTTP response which claims that there is a problem with "Product". In the list of allowed files, "Product" is also specified (in a new line). The same holds if I add a validation rule "Product" with "sometimes|array". 

I feel confident that the form with the specification stated above was working just a few weeks ago. Is it a problem on my side or is it a general bug caused by plugin changes or October/Laravel updates?

Thanks and best,
Tom

**Comment by skydiver** [comment]
Hello @tschmidleithner 

I can't reproduce the issue (build 419), this is my current config:

**Form:**
```
<form data-request="{{ emptyForm }}::onFormSubmit">
    {{ form_token() }}
    <div id="{{ __SELF__ }}_forms_flash"></div>
    <label><input class="form-check-input" type="checkbox" name="Product[]" value="Product1">Product 1</label>
    <label><input class="form-check-input" type="checkbox" name="Product[]" value="Product2">Product 2</label>
    <button id="simpleContactSubmitButton" type="submit" class="btn btn-default">Submit</button>
</form>
```
**Component config:**
```
[emptyForm]
rules[Product] = "required"
messages_success = "Your form was successfully submitted"
messages_errors = "There were errors with your submission"
inline_errors = "disabled"
allowed_fields[] = "Product"
anonymize_ip = "disabled"
recaptcha_theme = "light"
recaptcha_type = "image"
recaptcha_size = "normal"
```

I get a 406 error only if no products are selected, otherwise the selection is stored without problems.

Can you paste your component config?

**Comment by tschmidleithner** [comment]
Thanks @skydiver.

I had exactly the same configuration, except for the emptyForm component. I used the genericForm  component instead first and it didn't worked for my. Now I changed it to the emptyForm component and all is working as expected.

Thanks and best,
Tom
