### ISSUE TITLE
Add token to component settings

### ISSUE THREAD

**Issue by Alex360hd** [skydiver/october-plugin-forms#64]
Hello,

This issue about the possibility to give tokens/variables to the magic form component.

For example to have an email message corresponding to the "subject" field of the form, or adding the current date to the email subject, or defining the visitor email as the "reply-to" option see my  [reply-to](https://github.com/skydiver/october-plugin-forms/issues/60) issue.

What do you think about it ? Actually, the component settings is a little too static.

**Comment by Alex360hd** [comment]
Any update about this ?

I think about a way to dynamically define email recipients. That would allow to send the notification email to different addresses depending on the result of the form.

It would be useful for notification subject too, to make it dynamic.

Same for the group, that could depend on the result of the form instead of being static.

**Comment by skydiver** [comment]
Have you seen the new events feature?

You can "intercept" the form submission and do your own logic.

**Comment by Alex360hd** [comment]
Ah, I didn't see that, I will take a look.

**Comment by skydiver** [comment]
You need to create a new plugin.

On the boot method, add:

```
Event::listen('martin.forms.beforeSaveRecord', function ($formdata) {
    // add your custom logic here
});
```

You can take a look at [this plugin](https://github.com/therealkevinard/oc-plugin-rwm-mfcontactsview)

**Comment by Alex360hd** [comment]
Hello,

I looked at that new events, but I'm not sure it can do what I want.

I need to add the current date to the notification email subject, so I need to access to components settings as the subject of the notification message is done in the component.

the $formdata you have as argument only contains the form user data, I can't alter the email subject before sending it from here.

Another event like "beforeSendMail" is required with all mail object as argument to be able to alter before sending it.

**Comment by Alex360hd** [comment]
Any update on this ? Concretely, I need to have the current date to all email subjects I send. Even with the new event system, I don't see how can I do that. It seems to be impossible without hardcoding the plugin actually.
