### ISSUE TITLE
add plugin to snippet

### ISSUE THREAD

**Issue by carmeloMagna** [skydiver/october-plugin-forms#67]
Hi @skydiver,

thank you for you brilliant plugin. I need to use it within a snippet to add it to a customer static-page rainlab plugin.

In the snipped I have

```
<div class="step-by-spep-form">
    <h3>A STEP BY STEP FORM</h3>
    {% component 'customForm' subjects=requests %}
</div>
```

where requests is a list of different subjects to choose.

in the custom form I have (together with the genericForm view):

```
<div class="form-group dropdown">
        <label for="subject">Subject:</label>
        {% set foo = requests|split(',') %}
        {% set subjects = {'':'-- scegli un argometo --'} %}
        {% for subject in foo %}
            {% set key = subject|replace({' ':'_'}) %}
            {% set subjects = subjects|merge({ (key) : subject }) %}
        {% endfor %}
        <select name="subject" class="form-control">
                {% for key,subject in subjects %}
                    <option value="{{ key }}">{{ subject }}</option>
                {% endfor %}
        </select>
    </div>
```

Now I can select a list of subject by adding to the "subject" variable in the snippet a comma separated list of subjects.

Unfortunately the page respond me `AJAX handler 'customForm::onFormSubmit' was not found.`

It seems that the plugin is not registered. Can you help me?

Thank you!!

**Comment by skydiver** [comment]
Hello @carmeloMagna 

Are you including the component inside a partial?

**Comment by carmeloMagna** [comment]
Yes, I adding it inside a partial and then use the partial as a snippet for rainlab/pages

**Comment by carmeloMagna** [comment]
Hi @skydiver,

I resolved the problem by adding the component inspector inside the layout and not the partial. 

I don't know if it is the "best practice", but it works for me and is sufficient now.

If you have  any other solution, please, tell me.

Regards,

Carmelo

**Comment by skydiver** [comment]
Right, you cannot put component using ajax inside partials.

For more info, you can read [this thread](https://github.com/skydiver/october-plugin-forms/issues/13#issuecomment-272703708)
