### ISSUE TITLE
Better way to include javascript

### ISSUE THREAD

**Issue by Alex360hd** [skydiver/october-plugin-forms#68]
Hello,

I'm still playing with the module and I noticed that the javascript is included inside the emptyForm_forms_flash div.

I think you should find a better way to execute some JS when form is submitted (custom JS function, form reset, etc....) for several reasons :

* It's not a good practice to include javascript in the middle of the DOM.
* If you want to theme your form and don't want to include that empty div "emptyForm_forms_flash" you lost some functionnalities, which should never happens.

So I think that the javascript addition should be done in a separate way and the emptyForm_forms_flash div should only be used as a wrapper for the alert message.

Thanks

**Comment by skydiver** [comment]
Hello @Alex360hd 

You're right, it's not the best option.

For an advanced use, it's possible to use the [javascript api](https://octobercms.com/docs/ajax/javascript-api#global-events) of October and run your custom code when ajaxError event are triggered.
