### ISSUE TITLE
Custom alert partial or classes

### ISSUE THREAD

**Issue by trow-eu** [skydiver/october-plugin-forms#69]
Hello. Nice plugin, really love it.

Only issue I have at the moment - I want to use custom alert msg layout, but this partial (flash.htm) is called somewhere inside plugin and can't be rewritten by simply making some partial in my theme.

What is easy way to achieve this? 

And as proposition - make it possible to change Alert layout as easy as it is to make new forms with this plugin :)

**Comment by skydiver** [comment]
Hello @trow-eu 

This feature will be available on version 1.4.4 (still not estimated release date)

At this point the current versions are:
* 1.4.2 - stable
* 1.4.3 - edge

Feel free to test current master branch ...

![screenshot from 2017-08-30 10 58 24](https://user-images.githubusercontent.com/578784/29876079-2bdefa94-8d72-11e7-8d20-ae383c42176d.png)
