### ISSUE TITLE
Not sending emails or updating database "help wanted"

### ISSUE THREAD

**Issue by TrustyTristan** [skydiver/october-plugin-forms#70]
I have my component on the layout. 
The tag {% component 'footerContact' %} in the partial

Everything seems to work? the url updates with the form data but nothing goes into the database or is emailed to me. (I have notifications setup too)

https://dev.healthretreat.com.au/contact

**Comment by TrustyTristan** [comment]
Figured it out..

Eventually got to here:
https://octobercms.com/docs/ajax/introduction

Realised I didn't have `{% framework %}` included in my layout.

Other jquery stuff was working so didn't know this was a thing.

**Comment by skydiver** [comment]
Hello @TrustyTristan 

Glad to see you we're able to resolve your problem
