### ISSUE TITLE
form_data_arr does not allow to perform where request 

### ISSUE THREAD

**Issue by GeRoHi** [skydiver/october-plugin-forms#71]
Hello,

Maybe I'm wrong, but storing all the form datas in a jsoned array does not allow to use "where" clause when performing requests ?
Example : I use two extra fields in a generic upload form : user and activated, when I try to get records I can't filter on these.

Thanks in advance for your thoughts on this !

**Comment by skydiver** [comment]
Hello @GeRoHi 

Have you tried with events?

It's a powerful addition and you can write your own custom plugin, "intercept" form event and store on a your own table with your requirements.
