### ISSUE TITLE
An exception has been thrown during the rendering of a template ("The partial 'recaptcha' is not found.").

### ISSUE THREAD

**Issue by ajinkyakambe** [skydiver/october-plugin-forms#73]
<div class="form-group">
                  <textarea id="comments" name="comments" rows="8" cols="80"></textarea>
              </div>
  
         <div class="form-group">
        {% partial 'recaptcha' %}
    </div>
  
              <button id="simpleContactSubmitButton" type="submit" class="btn btn-default">Submit</button>
  
          </form>

Can you please help me with this problem ?

I am getting An exception has been thrown during the rendering of a template ("The partial 'recaptcha' is not found."). error. 

I did tried finding many things but i didn't worked out.

**Comment by skydiver** [comment]
Hello @ajinkyakambe 

1. which build are you using?
2. if you copy recaptcha.htm from component to your partial, the problem is solved?
3. can you try this code?:
```
{% partial __SELF__ ~ '::recaptcha' %}
```

**Comment by ajinkyakambe** [comment]
1] I am using the latest build.
2] I tried copying the recaptcha.htm from component to my theme, the problem is solved but I cannot see the ReCaptcha on the front end. When I saw the front end, I saw this 


<div class="form-group">
--
  | <div id="" class="g-recaptcha" data-sitekey="" data-theme="" data-type="" data-size=""></div>
  |  
  | </div>
  |  
  | <button id="simpleContactSubmitButton" type="submit" class="btn btn-default">Submit</button>
  |  
  | </form>



3] I tried using this code {% partial __SELF__ ~ '::recaptcha' %},

But it doesn't work. 
Still, i see. 
An exception has been thrown during the rendering of a template ("The partial 'recaptcha' is not found.").
H:\root\home\shelloman45-001\www\site3/themes/asaffa/pages/business-enquiries.htm line 167

My server is windows one.

**Comment by skydiver** [comment]
It's possible for you to test on a linux machine?

I don't have access to a windows pc to test if it's working ...

**Comment by MiguelDebruyne** [comment]
I have the same problem on OSX

- Place component on page
- Expand component via October texteditor
- Get this error

Didn't have this error when just drag n dropping it on the page
