### ISSUE TITLE
A better example for Usage

### ISSUE THREAD

**Issue by ghost** [skydiver/october-plugin-forms#75]
In documentation step 2 Usage , there is a link for "Override component HTML with your form". But that does not help. Can you give an example for overriding component HTML for General AJAX Form.

**Comment by skydiver** [comment]
Hello @rgucluer 

Override a component HTML is a October feature, this is why the link points to official documentation.

As i see, the difficulty is not plugin related, nevertheless, i'm going to create a blank theme to illustrate how to override HTML.

Hope to have this ready asap, i will notify you on this thread once is complete.

**Comment by rgucluer** [comment]
Thank you for your response. I managed to override but a help file would be great.

I used alias : contactForm for the component 

I created a partial : "partials/contactForm/default.htm" 

copied the code I extracted from the component 
  How: click the "component" text in {% component 'iletisimForm' %}
  then by clicking the top right icon(like git branch icon).
  Component code extract. Copy the extracted code.

Paste into partials/contactForm/default.htm

when I change code in partials/contactForm/default.htm
I see the result in my contact page.

**Comment by EleRam** [comment]
Usage steps are too complicated for newbie users.
Can you please explain the process of using this plugin?

for example: 
 in usage docs have this line `Drag selected component to your page`. but I didn't see any component that I can drag it!
