### ISSUE TITLE
How can we get the ID value in autoresponse templates?

### ISSUE THREAD

**Issue by rangrage** [skydiver/october-plugin-forms#77]
Hi, 

I have created a new mail template and have included the ID fields as so {{ id }} however this does not work when the email is sent. 

How can I access the record Id field in the autoresponse template please? 

Thanks.

**Comment by rangrage** [comment]
Any solution for this please?

**Comment by skydiver** [comment]
Hello @rangrage 

Will be fixed on a future version

**Comment by rangrage** [comment]
Thanks, looking forward to it soon :+1:

**Comment by skydiver** [comment]
@rangrage v1.4.5 was released
You can use {{id}} on your template

**Comment by rangrage** [comment]
Awesome! Thank you :1st_place_medal:
