### ISSUE TITLE
Cannot Upload

### ISSUE THREAD

**Issue by rangrage** [skydiver/october-plugin-forms#78]
Hi Martin, 

I am creating a new form with the upload component and when clicking on the upload files button nothing happens. 

When I checked the console it has the following error:
```
uploader.js:340 Uncaught TypeError: $(...).render is not a function
    at uploader.js:340
    at uploader.js:344
```

It's quite weird because I have used the component on another website which is working fine, I've followed the exact steps but can't get this working. 

Thanks for your help.

**Comment by rangrage** [comment]
This is not a problem with the plugin at all, I think the theme JS (bootstrap) is the issue here. 

If anyone has any solution for this kindly let me know please. 

Thanks.

**Comment by m2art** [comment]
What was solved your problem?

**Comment by m2art** [comment]
I have solved my issue. Problem was in my thema layout I forget added:

After all *.CSS linked:
`{% styles %}`

After all *.JS script: 
`{% scripts %}`

This two line of code solve my problems and now everything works correctly.
