### ISSUE TITLE
Error on form submit

### ISSUE THREAD

**Issue by jonathan-hc** [skydiver/october-plugin-forms#80]
Hi,

I'm facing an error on submitting the form. 

`AJAX handler 'genericForm::onFormSubmit' was not found.`

I am including the AJAX framework in the layout using

`{% framework extras %}`

Any idea what the issue might be? 

Thanks!

**Comment by skydiver** [comment]
Hello @jonathan-hc 

Sounds like you are adding the component to the partial.

Please, read issue https://github.com/skydiver/october-plugin-forms/issues/57

**Comment by jonathan-hc** [comment]
Thank you, @skydiver 
That was the issue.
