### ISSUE TITLE
Error on install

### ISSUE THREAD

**Issue by Everus** [skydiver/october-plugin-forms#81]
Hi,
I'm facing error when I try to install this plugin.
> "SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'json null, `ip` varchar(255) null, `deleted_at` timestamp null, `created_at` tim' at line 1 (SQL: create table `martin_forms_records` (`id` int unsigned not null auto_increment primary key, `form_data` json null, `ip` varchar(255) null, `deleted_at` timestamp null, `created_at` timestamp null, `updated_at` timestamp null) default character set utf8 collate utf8_unicode_ci engine = InnoDB)" on line 664 of /vendor/laravel/framework/src/Illuminate/Database/Connection.php

**Comment by skydiver** [comment]
Hello @Everus 

Which database engine are you using?
Which version?

Thanks.-

**Comment by Everus** [comment]
I use mysql:5.6 image for docker.

**Comment by blitzgucker** [comment]
Hi
You have to upgrade your mysql database. Json columns are supported from Version 5.7.
Temporary you can change the json column to a text column "$table->text('form_data')->nullable();" in the "create_records_table.php" file and it will work.

**Comment by skydiver** [comment]
I will change the migration to a text column...
