### ISSUE TITLE
Autoresponse mail template is not rendering field values

### ISSUE THREAD

**Issue by rangrage** [skydiver/october-plugin-forms#86]
Hi, 

I've just upgraded to October build 428 and updated the plugins as well. 

During testing I've notice that the **martin.forms::mail.autoresponse** does not output the field values as it did before. 

Can you kindly investigate this please? 

Thanks,

**Comment by skydiver** [comment]
Got build 430 and works fine.
Changed `martin.forms::mail.autoresponse` template to:

```
<h3>Name: {{ data.name }}</h3>

<p>Thank you for contacting us! We have received your request and are working on responding to you as soon as possible.</p>
<p>If you have any additional information to add to this case, please reply to this email.</p>
<p>Thanks in advance for your patience and support.</p>
```

And works as expected (using genericForm component)

**Comment by rangrage** [comment]
Excellent! Thank you mate :)
