### ISSUE TITLE
Input data to mail subject

### ISSUE THREAD

**Issue by cemik** [skydiver/october-plugin-forms#87]
Hi, love your plugin and approach of storing and handling data from forms. However I'm lost when I try to get input data from the forms to render in mail templates subject. Can you give som input on if that's possible and how to accomplish it?

Best regards

Micke

**Comment by skydiver** [comment]
Hey @cemik 

You can check this question: https://github.com/skydiver/october-plugin-forms/issues/86

**Comment by cemik** [comment]
ok, thanks! Got it working with custom mail templates. 
But can you set it also by adding data to the custom subject function in component, and use default notifications mail template?

**Comment by skydiver** [comment]
Hey @cemik 

Can you elaborate a little more your idea?

Thanks.-

**Comment by cemik** [comment]
Sorry for late respons,

I was thinking something like provided screenshot, where I set the subject with a data entry from the form. That way you can use a default template with custom subjects.

![image](https://user-images.githubusercontent.com/15110639/36678568-69f5c150-1b11-11e8-86d0-529e0e17438b.png)

**Comment by Alex360hd** [comment]
+1 to this, except that I suggest to use twig style token as october is based on twig.

    Something like Example with {{ data.id }}

**Comment by skydiver** [comment]
This will be added on the next version.
Thanks to @Alex360hd ...
