### ISSUE TITLE
"Form session expired! Please refresh the page."

### ISSUE THREAD

**Issue by Flow999Cloud** [skydiver/october-plugin-forms#88]
Awesome plugin! 

I have some problems though, @skydiver 
When I click on the form submit button, it says me as following;
"Form session expired! Please refresh the page."
I entered the contents around in 15 secs, FYI.
Also I added the {{ form_token() }} code to the form section as well due to the [Denis Smirnov's feedback.](https://octobercms.com/plugin/martin-forms#reviews)

Is there way to solve this problem?

This is the code I used.
```HTML
<form data-request="{{ emptyForm }}::onFormSubmit">
        {{ form_token() }}
        <div id="{{ emptyForm }}_forms_flash"></div>
        <!-- YOUR FORM FIELDS -->
        {% partial 'recaptcha' __SELF__=emptyForm %}
        <!-- SUBMIT BUTTON -->
</form>
  ```

**Comment by Flow999Cloud** [comment]
<form data-request="{{ __SELF__ }}::onFormSubmit">
    {{ form_token() }}
    <div id="{{ __SELF__ }}_forms_flash"></div>
    <div class="form-group">
        <label class="sr-only" for="name">Name</label>
        <input type="text" id="name" name="name" placeholder="Name*" class="form-control input-lg">
        <span class="help-block">
            <div data-validate-for="name"></div>
        </span>
    </div>
    <div class="form-group">
        <label class="sr-only" for="email">Email</label>
        <input type="text" id="email" name="email" placeholder="E-Mail*" class="form-control input-lg">
        <span class="help-block">
            <div data-validate-for="email"></div>
        </span>
    </div>
    <div class="form-group">
        <label class="sr-only" for="phone-number">Phone number</label>
        <input type="text" id="phone-number" name="phone-number" placeholder="Phone number*" class="form-control input-lg">
        <span class="help-block">
            <div data-validate-for="phone-number"></div>
        </span>
    </div>
</form>

**Comment by skydiver** [comment]
Hello @Flow999Cloud 

 Can you test using this code: https://github.com/skydiver/october-plugin-forms/blob/master/components/genericform/default.htm

**Comment by Flow999Cloud** [comment]
Thanks, @skydiver 
It is working now well.
