### ISSUE TITLE
UploadForm not saving attachments

### ISSUE THREAD

**Issue by rangrage** [skydiver/october-plugin-forms#89]
Hi @skydiver

I've had an upload form which was working fine previously, but for some reason now it does not send the attachment via email notification and also not stored in the backend. I am on October Build 431. 

Can you kindly check on this issue please?

**Comment by skydiver** [comment]
Hello @rangrage 

I've installed a fresh october, upgraded to build 431 and installed the plugin.

The upload was working fine.

**Comment by rangrage** [comment]
Hi @skydiver 

Yes, the upload works fine, but when I send the message; the attachment is not sent via email and it is also not stored in the backend Records. 

I have tested this on 3 different servers and all have the same result. Can you please confirm that it is sending the attachment for you? And if so, what could I do to figure out why I'm having this issue please? 

Thanks for your help.

**Comment by rangrage** [comment]
@skydiver I have discovered that the problem is with overriding the component partial. 

The upload only sends the attachment if the form uses the twig tags i.e. 
```{{ form_ajax(__SELF__ ~ '::onFormSubmit') }}```

and it doesn't work when using the standard html form tags 
```<form data-request="{{ __SELF__ }}::onFormSubmit" data-request-flash>```

So, can you tell me how to add **`data-request-flash`** to the twig form tags please? 

Thanks,

**Comment by skydiver** [comment]
Hello @rangrage 

Please, check October documentation before ask: https://octobercms.com/docs/markup/function-form

Anyway, you need to call like this:
```
{{ form_ajax(__SELF__ ~ '::onFormSubmit', { "data-request-flash": 'your-value'}) }}
```

**Comment by rangrage** [comment]
Hi @skydiver 

I obviously had a look at the October documentation first and I had tried the example from the documentation but that doesn't work. 

After digging through the October issues I was able to find the correct method of adding this. 

`{{ form_ajax(__SELF__ ~ '::onFormSubmit', {flash : ''}) }}`

Thanks,

**Comment by skydiver** [comment]
Glad to see you have solved the problem @rangrage
