### ISSUE TITLE
close button doesn't work

### ISSUE THREAD

**Issue by grigkar** [skydiver/october-plugin-forms#91]
Hi all,
I'm using for my forms the default flash message window. On clicking to close button - nothing happened. 
`<button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">×</span></button>`
I'm using framework extras in head tag right after jquery 3.3.1. 
How to solve this?

And also get 406 (Not Acceptable) error after clicking submit button (but email goes fine)
<img width="175" alt="screenshot at jan 26 16-16-48" src="https://user-images.githubusercontent.com/3725153/35441426-84897824-02b4-11e8-82e2-e48fd9e22a31.png">
<img width="637" alt="screenshot at jan 26 16-16-36" src="https://user-images.githubusercontent.com/3725153/35441432-87b7797e-02b4-11e8-8407-94e237af638d.png">

**Comment by skydiver** [comment]
Hello @grigkar 

Are you using bootstrap?

**Comment by grigkar** [comment]
@skydriver yes. But I removed this plugin and created my own

**Comment by skydiver** [comment]
Sounds great.

**Comment by MiguelDebruyne** [comment]
We shouldn't worry about the 406 message then? I included bootstap.js to check if it removed the erorr but it's still there.

jquery.js
`xhr.send( options.hasContent && options.data || null );`

> Failed to load resource: the server responded with a status of 406 (Not Acceptable)

**Comment by sumerian-1** [comment]
I have the same issue. I'm not using Bootstrap. No js errors in browser console.
