### ISSUE TITLE
Wrong email subject

### ISSUE THREAD

**Issue by Alex360hd** [skydiver/october-plugin-forms#92]
Hello,

Don't know if the cause is a recent update of october or magic form plugin itself, but the email notification subject stopped working.

Even when you define a subject for notifications in the component, for exemple "Contact Form", when I send the email and look in my mailbox for the result, the real subject of the email is : 

    Magic Forms :: new form submited

To reproduct, just config the component to send email notification, define a subject, and send you an email.

**Comment by skydiver** [comment]
Hello @Alex360hd 

I've tested on a clean October install and seems to works fine.

This is my config:

![image](https://user-images.githubusercontent.com/578784/36338889-93bb80b8-1398-11e8-85f4-27d14b30af1c.png)

and this is how i get the test email:

![image](https://user-images.githubusercontent.com/578784/36338898-b2be5fbc-1398-11e8-83f4-66dc1651d06f.png)

**Comment by Alex360hd** [comment]
The title of the email is ok, but the title of the default email template is still : 

> Magic Forms :: new form submited

See attached screenshot
![capture](https://user-images.githubusercontent.com/15909570/38676572-bd93f8be-3e5b-11e8-84fc-a81ee2a071e2.PNG)

**Comment by skydiver** [comment]
This will be in the next release
