### ISSUE TITLE
Not able to reset form after submission

### ISSUE THREAD

**Issue by Manojython** [skydiver/october-plugin-forms#93]
I did choose reset form option in the component but it doesn't seem to reset the form.
How is it done?
Do we need to add anything in the html field as well?

**Comment by Manojython** [comment]
was missing a div which calls the reset function

**Comment by Badlapje** [comment]
which div was it @Manojython ?  I have the same problem

**Comment by Manojython** [comment]
When u drag and drop the component, fork it. You will find whichever is missing.
