### ISSUE TITLE
Redirect validation

### ISSUE THREAD

**Issue by EleRam** [skydiver/october-plugin-forms#94]
Why you tried to validate `redirect` property as a URL while `Redirect::to` will get a page also?
```PHP
// it could be a page name/path
Redirect::to('mypagename');
```

```PHP
// CHECK FOR REDIRECT
if (filter_var($redirect, FILTER_VALIDATE_URL)) {
    return Redirect::to($redirect);
}
```

sorry for my English! :)

**Comment by skydiver** [comment]
Excellen point @EleRam 

I will say the idea was to prevent an invalid URL, but i think it's a great suggestion.
