### ISSUE TITLE
Javascript error: TypeError in no skipurl defined

### ISSUE THREAD

**Issue by JurekRaben** [skydiver/october-plugin-forms#95]
If you do not define a skipurl, the uploadform will throw a javascript error:

```javascript
TypeError: url.indexOf is not a function. (In 'url.indexOf(skipUrl)', 'url.indexOf' is undefined)
```

**Comment by skydiver** [comment]
Hello @JurekRaben 

How i can reproduce this error?

Thanks.-

**Comment by JurekRaben** [comment]
Hi,

I did not define routing or skipurls simply, and used the file upload form using ajax.

**Comment by skydiver** [comment]
Hey @JurekRaben 

I don't see the word "skipUrl" on the whole code.

Are you sure is the plugin the cause of the error?

**Comment by JurekRaben** [comment]
Ah, no, not really. It’s an anonymous function, maybe it was caused by debugbar then. Will check that later.

**Comment by JurekRaben** [comment]
Yes, it’s a problem of debugbar. Sorry then :)
